Instalación de librerias para exploración

In [ ]:
pip install pandas openpyxl xlrd pyxlsb

In [ ]:
pip install xlrd

In [10]:
#Este apartado se encarga de cargar el archivo excel y mostrar las hojas que contiene
import pandas as pd
from pathlib import Path


archivo = Path("../data/raw/FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx")

xls = pd.ExcelFile(archivo)

xls.sheet_names

['BALANCE',
 'PYG',
 'BALANCE %',
 'EPyG %',
 'CONSCOND',
 'RK',
 'Gráficos RK',
 'COMPOS CART',
 'COMPOS CART %',
 'MET',
 'INDICADORES',
 'REP GERENCIAL']

In [ ]:
#Recorremos cada hoja del archivo y mostramos las primeras filas para entender su estructura
for hoja in xls.sheet_names:
    df_temp = pd.read_excel(archivo, sheet_name=hoja, header=None)
    print("HOJA:", hoja)
    print("Filas:", df_temp.shape[0], "Columnas:", df_temp.shape[1])
    display(df_temp.head(15))

HOJA: BALANCE
Filas: 1399 Columnas: 35

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,ESTADO DE SITUACIÓN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,NaN,ACTIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,11,FONDOS DISPONIBLES,962844.36003,774077.6831,1913012.73986,1021324.78103,4671259.56402,530918.75278,580471.74464,...,15625.79264,42802.81765,11688.15365,308086.99488,7854033.5085,895042.47981,380511.87832,0,27313.94629,6551165.20408
10,NaN,1101,Caja,202958.75959,276232.61409,321160.33829,92656.11901,893007.83098,89082.34343,125314.40563,...,873.67445,5211.29962,1832.63559,27061.76074,1303829.79611,81120.62946,16218.79754,0,2706.31004,1203784.05907
11,NaN,110105,Efectivo,202958.75959,276232.61409,321104.63829,92656.11901,892952.13098,89081.74343,125314.40563,...,873.67445,5205.69962,1819.43559,27024.86964,1303705.13535,81112.49946,16214.85644,0,2693.11004,1203684.66941
12,NaN,110110,Caja chica,0,0,55.7,0,55.7,0.6,0,...,0,5.6,13.2,36.8911,124.66076,8.13,3.9411,0,13.2,99.38966
13,NaN,1102,Depósitos para encaje,304412.00314,384760.1572,685536.21093,330346.65553,1705055.0268,156029.0075,163538.45422,...,6618.21296,17947.60075,3848.43766,111541.50726,2878840.56762,431451.86148,144549.60466,0,10466.65062,2292372.45086
14,NaN,110205,Banco Central del Ecuador,304411.8188,384760.1572,685536.21093,330346.65553,1705054.84246,156029.0075,163538.45422,...,6618.21296,17947.60075,3848.43766,111541.50726,2878839.38328,431451.86148,144549.60466,0,10466.65062,2292371.26652

HOJA: PYG
Filas: 143 Columnas: 35

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,ESTADO DE PÉRDIDAS Y GANANCIAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,5,INGRESOS,300246.30469,306478.04783,662033.5339,226361.96458,1495119.851,101517.44945,131702.24643,...,4145.07324,10936.4479,9117.46733,67163.07144,2237170.26246,147054.75722,198386.82175,0,13262.54057,1878466.14292
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,51,INTERESES Y DESCUENTOS GANADOS,209548.29514,197945.78492,458693.50415,158770.44065,1024958.02486,70719.74901,99946.68116,...,3237.11205,8130.97679,7941.45775,52445.66798,1543230.62188,110501.51751,107561.38728,0,11178.5698,1313989.14729
11,NaN,5101,Depósitos,615.8344,723.96593,7710.45246,2449.65074,11499.90353,1549.07222,1011.26186,...,33.35165,44.36282,14.99028,810.38392,18713.47608,2017.81122,919.09567,0,48.34193,15728.22726
12,NaN,5102,Operaciones interbancarias,0,0,9.72221,0,9.72221,0,0.55556,...,0,0,0,0,10.27777,0,0,0,0,10.27777
13,NaN,5103,INTERESES y descuentos de inversiones en títul...,20781.06571,16951.98117,36882.74422,6577.34099,81193.13209,8303.17798,5224.56618,...,720.98356,513.51282,23.70369,4981.7389,120549.76165,11901.87965,4951.60038,0,744.68725,102951.59437
14,NaN,5104,INTERESES Y DESCUENTOS DE CARTERA DE CRÉDITOS,186896.31773,180241.91735,413798.66009,149743.44892,930680.34409,60865.11417,93583.61512,...,2482.77684,7573.10115,7902.76378,46235.02202,1401326.29068,96188.86364,101575.35169,0,10385.54062,1193176.53473

HOJA: BALANCE %
Filas: 87 Columnas: 35

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,ESTADO DE SITUACIÓN CONSOLIDADO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,(en porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,NaN,ACTIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,11,FONDOS DISPONIBLES,0.092086,0.075583,0.085617,0.111029,0.089419,0.150484,0.092391,...,0.10452,0.129024,0.066623,0.130082,0.098955,0.126163,0.079217,0,0.084059,0.097565
10,NaN,12,OPERACIONES INTERBANCARIAS,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,NaN,13,INVERSIONES,0.177986,0.217013,0.248187,0.156674,0.21191,0.191206,0.185545,...,0.332933,0.196879,0.033111,0.211553,0.196424,0.174208,0.112696,0,0.171056,0.204883
12,NaN,NaN,INVERSIONES DEL SECTOR PRIVADO,0.014877,0.04519,0.035162,0.075689,0.040204,0.064396,0.023118,...,0.157406,0.13332,0,0.122243,0.043483,0.068673,0.015322,0,0.072421,0.042696
13,NaN,NaN,INVERSIONES DEL SECTOR PUBLICO,0.153315,0.114329,0.186364,0.066167,0.144462,0.104401,0.144968,...,0.162568,0.063559,0.031342,0.085704,0.130909,0.099996,0.08097,0,0.091717,0.137937
14,NaN,1307,De disponibilidad restringida,0.009802,0.057772,0.029191,0.014821,0.028383,0.022906,0.017643,...,0.01296,0,0.001769,0.003752,0.022848,0.005538,0.016828,0,0.006918,0.025185

HOJA: EPyG %
Filas: 117 Columnas: 35

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,ESTADO DE PÉRDIDAS Y GANANCIAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,(en porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,NaN,TOTAL INGRESOS,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,51,INTERESES Y DESCUENTOS GANADOS,0.697921,0.645873,0.692855,0.701401,0.685536,0.696627,0.758884,...,0.780954,0.743475,0.871016,0.780871,0.689814,0.751431,0.54218,0,0.842868,0.699501
11,NaN,5101,Depósitos,0.002051,0.002362,0.011647,0.010822,0.007692,0.015259,0.007678,...,0.008046,0.004056,0.001644,0.012066,0.008365,0.013721,0.004633,0,0.003645,0.008373
12,NaN,5102,Operaciones interbancarias,0,0,0.000015,0,0.000007,0,0.000004,...,0,0,0,0,0.000005,0,0,0,0,0.000005
13,NaN,5103,INTERESES y descuentos de inversiones en títul...,0.069213,0.055312,0.055711,0.029057,0.054305,0.081791,0.03967,...,0.173937,0.046954,0.0026,0.074174,0.053885,0.080935,0.024959,0,0.05615,0.054806
14,NaN,5104,INTERESES Y DESCUENTOS DE CARTERA DE CRÉDITOS,0.622477,0.588107,0.625042,0.661522,0.622479,0.599553,0.71057,...,0.598971,0.692464,0.866772,0.688399,0.626383,0.654102,0.512007,0,0.783073,0.635187

HOJA: CONSCOND
Filas: 100 Columnas: 35

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,ESTADO DE SITUACIÓN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,CONSCOND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PEQUEÑOS,BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
9,NaN,NaN,ACTIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,11,FONDOS DISPONIBLES,962844.36003,774077.6831,1913012.73986,1021324.78103,4671259.56402,530918.75278,580471.74464,...,15625.79264,42802.81765,11688.15365,308086.99488,7854033.5085,895042.47981,380511.87832,0,27313.94629,6551165.20408
11,NaN,12,OPERACIONES INTERBANCARIAS,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,NaN,13,INVERSIONES,1860997.95365,2222512.48075,5545465.9726,1441204.31955,11070180.72655,674590.04705,1165732.61784,...,49773.53408,65313.05469,5808.84926,501040.61813,15590052.88774,1235885.47882,541323.78495,0,55582.38334,13757261.24063
13,NaN,NaN,INVERSIONES DEL SECTOR PRIVADO,155549.61578,462813.54507,785665.32412,696246.05073,2100274.5357,227194.19219,145243.93044,...,23532.22431,44227.91448,0,289520.29145,3451204.4312,487189.81341,73598.57359,0,23532.22431,2866883.81989
14,NaN,NaN,INVERSIONES DEL SECTOR PUBLICO,1603044.48845,1170889.29982,4164100.2324,608654.99364,7546689.01431,368334.51802,910799.73583,...,24303.85231,21085.14021,5498.48726,202980.77097,10390218.93241,709406.461,388930.8662,0,29802.33957,9262079.26564

HOJA: RK
Filas: 170 Columnas: 13

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,RANKING EN BASE A LA PARTICIPACIÓN DE LAS PRIN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,(en miles de dólares y porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,ACTIVOS,NaN,NaN,NaN,NaN,NaN,NaN,PASIVOS,NaN,NaN,NaN
8,NaN,ENTIDADES,February 2026 (USD),February 2026 (%),March 2026 (USD),March 2026 (%),NaN,NaN,ENTIDADES,February 2026 (USD),February 2026 (%),March 2026 (USD),March 2026 (%)
9,NaN,BP PICHINCHA,22074377.64393,0.281841,22343920.0077,0.281517,NaN,NaN,BP PICHINCHA,19886214.75949,0.282311,20142446.93146,0.281889
10,NaN,BP GUAYAQUIL,10157285.2624,0.129686,10455869.40551,0.131736,NaN,NaN,BP GUAYAQUIL,9281473.36809,0.131763,9564681.12603,0.133856
11,NaN,BP PACIFICO,10279226.01753,0.131243,10241398.01567,0.129034,NaN,NaN,BP PACIFICO,9126046.71567,0.129556,9063587.33015,0.126843
12,NaN,BP PRODUBANCO,9033400.68523,0.115336,9198745.81122,0.115898,NaN,NaN,BP PRODUBANCO,8289352.61722,0.117678,8469818.3594,0.118533
13,NaN,BP BOLIVARIANO,6245400.87468,0.07974,6282749.33816,0.079158,NaN,NaN,BP BOLIVARIANO,5646300.96297,0.080157,5676796.56967,0.079446
14,NaN,BP INTERNACIONAL,6036748.08137,0.077076,6208414.95569,0.078222,NaN,NaN,BP INTERNACIONAL,5453674.54417,0.077422,5649993.44537,0.079071

HOJA: Gráficos RK
Filas: 0 Columnas: 0

Empty DataFrame
Columns: []
Index: []

HOJA: COMPOS CART
Filas: 238 Columnas: 35

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,COMPOSICIÓN DE LA CARTERA DE CRÉDITOS POR VENC...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,En miles de dólares,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,NaN,CARTERA BRUTA,7216997.34169,6941553.23693,14176489.30606,6557014.39631,34892054.28099,1929357.79356,4264921.97976,...,71217.23852,224308.82723,163112.27159,1439681.3171,53285881.6935,4821777.99714,3793838.5237,0,234329.51011,44435935.66255
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,1401,CARTERA DE CRÉDITOS PRODUCTIVO POR VENCER,3570271.91393,2711446.33794,5226037.93322,3869561.53627,15377317.72136,563799.23822,3001582.82332,...,8361.46358,26572.10207,0,515266.9223,24368883.22083,3918933.08707,280042.81759,0,8361.46358,20161545.85259
11,NaN,1402,CARTERA DE CRÉDITOS DE CONSUMO POR VENCER,2777304.28279,3204157.29863,4898911.46846,1927016.24429,12807389.29417,1119224.73648,1010836.92554,...,20090.21018,86473.09983,6315.2017,306802.99606,19507168.80248,596105.71241,2931864.45584,0,26405.41188,15952793.22235
12,NaN,1403,CARTERA DE CRÉDITOS INMOBILIARIO POR VENCER,205603.9149,474414.00621,931414.0671,301898.61589,1913330.6041,53622.91245,167876.31134,...,124.24124,32870.53556,0,63113.04641,2562428.76381,148562.06739,115742.15734,0,124.24124,2298000.29784
13,NaN,1404,CARTERA DE CRÉDITOS PARA MICROCRÉDITO POR VENCER,403178.81493,19080.06379,1924055.22888,63041.94205,2409356.04965,12631.43258,1030.78241,...,37971.66876,51055.98243,148280.0772,423000.32308,3305904.34786,5874.44529,11726.83343,0,186251.74596,3102051.32318
14,NaN,1408,CARTERA DE CRÉDITO DE VIVIENDA DE INTERÉS SOCI...,0,2905.21238,9288.45734,0,12193.66972,0,0,...,0,0,0,0,23021.77834,281.99929,10546.10933,0,0,12193.66972

HOJA: COMPOS CART %
Filas: 155 Columnas: 35

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,COMPOSICIÓN DE LA CARTERA DE CRÉDITOS POR VENC...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,(en porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,NaN,CARTERA BRUTA,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,1401,CARTERA DE CRÉDITOS PRODUCTIVO POR VENCER,0.494703,0.390611,0.368641,0.590141,0.440711,0.292221,0.703784,...,0.117408,0.118462,0,0.357903,0.457323,0.812757,0.073815,0,0.035683,0.453722
11,NaN,1402,CARTERA DE CRÉDITOS DE CONSUMO POR VENCER,0.384828,0.461591,0.345566,0.293886,0.367057,0.580102,0.237012,...,0.282098,0.385509,0.038717,0.213105,0.366085,0.123628,0.772796,0,0.112685,0.359007
12,NaN,1403,CARTERA DE CRÉDITOS INMOBILIARIO POR VENCER,0.028489,0.068344,0.065701,0.046042,0.054836,0.027793,0.039362,...,0.001745,0.146541,0,0.043838,0.048088,0.030811,0.030508,0,0.00053,0.051715
13,NaN,1404,CARTERA DE CRÉDITOS PARA MICROCRÉDITO POR VENCER,0.055865,0.002749,0.135722,0.009614,0.069052,0.006547,0.000242,...,0.533181,0.227615,0.909068,0.293815,0.062041,0.001218,0.003091,0,0.794828,0.06981
14,NaN,1408,CARTERA DE CRÉDITO DE VIVIENDA DE INTERÉS SOCI...,0,0.000419,0.000655,0,0.000349,0,0,...,0,0,0,0,0.000432,0.000058,0.00278,0,0,0.000274

HOJA: MET
Filas: 203 Columnas: 35

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,METODOLOGÍA CALCULO INDICADORES FINANCIEROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,MET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
9,NaN,NaN,ACTIVOS LIQUIDOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,11,FONDOS DISPONIBLES,962844.36003,774077.6831,1913012.73986,1021324.78103,4671259.56402,530918.75278,580471.74464,...,15625.79264,42802.81765,11688.15365,308086.99488,7854033.5085,895042.47981,380511.87832,0,27313.94629,6551165.20408
11,NaN,1201,Fondos interbancarios vendidos,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,NaN,130105,De 1 a 30 días,0,0,0,0,0,36000,0,...,0,0,0,0,137925.58904,101925.58904,0,0,0,36000
13,NaN,130205,De 1 a 30 días,73620.65378,0,0,0,73620.65378,0,0,...,0,0,0,0,94505.62478,20884.971,0,0,0,73620.65378
14,NaN,130305,De 1 a 30 días,54923.17917,99581.02427,39553.83681,385766.35734,579824.39759,38132.58873,60185.51731,...,7797.68393,21372.43541,0,182673.29889,1007130.46786,92936.95546,10090.43093,0,7797.68393,896305.39754

HOJA: INDICADORES
Filas: 80 Columnas: 34

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,INDICADORES FINANCIEROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,(En porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NOMBRE DEL INDICADOR,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,BP CITIBANK,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,SUFICIENCIA PATRIMONIAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILI...,2.431012,4.088927,34.881393,3.481837,5.392486,0.828583,3.883123,-48.596892,...,0.924906,2.556251,23.291996,1.914036,4.144089,7.588859,3.764319,0,2.69822,4.011342
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,ESTRUCTURA Y CALIDAD DE ACTIVOS:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,0.087592,0.094119,0.049942,0.073313,0.070254,0.172191,0.075263,0.096769,...,0.135222,0.116259,0.038628,0.118368,0.079453,0.08873,0.074656,0,0.08307,0.078799
14,NaN,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,0.912408,0.905881,0.950058,0.926687,0.929746,0.827809,0.924737,0.903231,...,0.864778,0.883741,0.961372,0.881632,0.920547,0.91127,0.925344,0,0.91693,0.921201

HOJA: REP GERENCIAL
Filas: 97 Columnas: 35

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,REPORTE GERENCIAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,(en miles de dólares y en porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,NaN,ACTIVO,10455869.40551,10241398.01567,22343920.0077,9198745.81122,52239933.2401,3528072.99421,6282749.33816,...,149500.0102,331742.01781,175437.37605,2368398.25283,79369588.21617,7094314.38269,4803400.47716,0,324937.38625,67146935.97007
9,NaN,NaN,% de participación del activo en el sistema,0.131736,0.129034,0.281517,0.115898,0.658186,0.044451,0.079158,...,0.001884,0.00418,0.00221,0.02984,1,0.089383,0.060519,0,0.004094,0.846003
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,11,FONDOS DISPONIBLES,962844.36003,774077.6831,1913012.73986,1021324.78103,4671259.56402,530918.75278,580471.74464,...,15625.79264,42802.81765,11688.15365,308086.99488,7854033.5085,895042.47981,380511.87832,0,27313.94629,6551165.20408
13,NaN,1102,Depósitos para encaje,304412.00314,384760.1572,685536.21093,330346.65553,1705055.0268,156029.0075,163538.45422,...,6618.21296,17947.60075,3848.43766,111541.50726,2878840.56762,431451.86148,144549.60466,0,10466.65062,2292372.45086
14,NaN,110310,Bancos e instituciones financieras locales,28355.43143,9058.76813,824910.61156,163498.62224,1025823.43336,182756.74915,148467.67109,...,8133.90523,15393.29374,6007.0804,150070.32045,1961091.78698,118726.81849,156702.44909,0,14140.98563,1671521.53377

In [12]:
#Elegimos la hoja que contiene la palabra "ACTIVO" para analizar su contenido
for hoja in xls.sheet_names:
    df = pd.read_excel(archivo, sheet_name=hoja, header=None)
    
    coincidencias = df.apply(
        lambda col: col.astype(str).str.contains("ACTIVO", case=False, na=False)
    )
    
    if coincidencias.any().any():
        print("Encontrado en hoja:", hoja)

Encontrado en hoja: BALANCE
Encontrado en hoja: PYG
Encontrado en hoja: BALANCE %
Encontrado en hoja: EPyG %
Encontrado en hoja: CONSCOND
Encontrado en hoja: RK
Encontrado en hoja: COMPOS CART %
Encontrado en hoja: MET
Encontrado en hoja: INDICADORES
Encontrado en hoja: REP GERENCIAL

In [14]:
#Una vez identificada la hoja que contiene la palabra "ACTIVO", cargamos esa hoja para analizar su contenido
hoja = "BALANCE"

df = pd.read_excel(archivo, sheet_name=hoja, header=None)

pd.set_option("display.max_rows", 80)
pd.set_option("display.max_columns", 50)

df.head(80)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,ESTADO DE SITUACIÓN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,BP CITIBANK,BP DINERS,BP GENERAL RUMIÑAHUI,BP INTERNACIONAL,BP LOJA,BP MACHALA,BP SOLIDARIO,BANCOS PRIVADOS MEDIANOS,BP PROCREDIT,BP AMAZONAS,BP BANCO COMERCIAL DE MANABI,BP LITORAL,BP COOPNACIONAL,BP CAPITAL,BP DELBANK,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,NaN,ACTIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,11,FONDOS DISPONIBLES,962844.36003,774077.6831,1913012.73986,1021324.78103,4671259.56402,530918.75278,580471.74464,154087.561,167846.30716,208702.64099,740954.91881,215386.4228,202028.38329,74290.21813,2874686.9496,81402.32482,62943.14724,16815.9418,3962.93017,57257.35337,7346.76897,8241.76457,15625.79264,42802.81765,11688.15365,308086.99488,7854033.5085,895042.47981,380511.87832,0,27313.94629,6551165.20408
10,NaN,1101,Caja,202958.75959,276232.61409,321160.33829,92656.11901,893007.83098,89082.34343,125314.40563,103.477,2.9,15700.94335,81017.15246,31593.05092,22143.37743,18802.55417,383760.20439,5564.07035,2864.12127,1882.22756,514.95419,6720.39379,322.2628,1276.12112,873.67445,5211.29962,1832.63559,27061.76074,1303829.79611,81120.62946,16218.79754,0,2706.31004,1203784.05907
11,NaN,110105,Efectivo,202958.75959,276232.61409,321104.63829,92656.11901,892952.13098,89081.74343,125314.40563,103.477,0,15700.54335,81009.02246,31591.67092,22142.81777,18784.45417,383728.13473,5564.07035,2863.72127,1881.22756,514.31309,6705.39379,321.6128,1275.72112,873.67445,5205.69962,1819.43559,27024.86964,1303705.13535,81112.49946,16214.85644,0,2693.11004,1203684.66941
12,NaN,110110,Caja chica,0,0,55.7,0,55.7,0.6,0,0,2.9,0.4,8.13,1.38,0.55966,18.1,32.06966,0,0.4,1,0.6411,15,0.65,0.4,0,5.6,13.2,36.8911,124.66076,8.13,3.9411,0,13.2,99.38966
13,NaN,1102,Depósitos para encaje,304412.00314,384760.1572,685536.21093,330346.65553,1705055.0268,156029.0075,163538.45422,86737.429,104089.9009,37458.35463,344714.43248,98907.06436,53490.13511,17279.25536,1062244.03356,30706.85064,26083.8668,7074.30857,3001.34913,9061.81824,4916.25104,2282.81147,6618.21296,17947.60075,3848.43766,111541.50726,2878840.56762,431451.86148,144549.60466,0,10466.65062,2292372.45086
14,NaN,110205,Banco Central del Ecuador,304411.8188,384760.1572,685536.21093,330346.65553,1705054.84246,156029.0075,163538.45422,86737.429,104089.9009,37458.35463,344714.43248,98906.06436,53490.13511,17279.25536,1062243.03356,30706.85064,26083.8668,7074.30857,3001.34913,9061.81824,4916.25104,2282.81147,6618.21296,17947.60075,3848.43766,111541.50726,2878839.38328,431451.86148,144549.60466,0,10466.65062,2292371.26652
15,NaN,110210,Banco Nacional de Fomento,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
16,NaN,110215,Bancos locales,0.18434,0,0,0,0.18434,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.18434,0,0,0,0,0.18434
17,NaN,1103,Bancos y otras instituciones financieras,413580.15159,98219.39216,860230.87901,556289.00189,1928319.42465,279845.16974,263662.71756,65870.568,63753.50626,154639.54206,289214.65301,84877.30752,122567.97512,37709.25571,1362140.69498,43754.61279,33784.86652,7485.04455,266.28402,41467.41895,2108.17383,4578.57643,8133.90523,19619.306,6007.0804,167205.26872,3457665.38835,355085.22101,218659.33234,0,14140.98563,2869779.84937
18,NaN,110305,Banco Central del Ecuador,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,NaN,110310,Bancos e instituciones financieras locales,28355.43143,9058.76813,824910.61156,163498.62224,1025823.43336,182756.74915,148467.67109,16370.919,56781.51872,99654.64635,102355.89949,53043.07867,109931.49328,15836.05742,785198.03317,34008.37528,31532.41884,6675.89145,266.28402,41467.41895,2099.29955,4486.35299,8133.90523,15393.29374,6007.0804,150070.32045,1961091.78698,118726.81849,156702.44909,0,14140.98563,1671521.53377
20,NaN,110315,Bancos e instituciones financieras del exterior,385224.72016,89160.62403,35320.26745,392790.37965,902495.99129,97088.42059,115195.04647,49499.649,6971.98754,54984.89571,186858.75352,31834.22885,12636.48184,21873.19829,576942.66181,9746.23751,2252.44768,809.1531,0,0,8.87428,92.22344,0,4226.01226,0,17134.94827,1496573.60137,236358.40252,61956.88325,0,0,1198258.3156
21,NaN,110320,EXCEDENTE DE FONDO DE LIQUIDEZ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,NaN,1104,Efectos de cobro inmediato,41893.44571,14865.51965,46085.31163,41877.93002,144722.20701,5962.23211,27903.37023,1376.087,0,903.80095,26008.68086,0,2301.55113,499.15289,64954.87517,1376.79104,210.29265,373.95312,180.33283,7.72239,0.0813,104.25555,0,24.61128,0,2278.04016,211955.12234,27384.76786,1084.13378,0,0,183486.2207
23,NaN,1105,Remesas en tránsito,0,0,0,155.07458,155.07458,0,52.797,0,0,0,0,9,1525.3445,0,1587.1415,0,0,0.408,0.01,0,0,0,0,0,0,0.418,1742.63408,0,0.01,0,0,1742.62408
24,NaN,110505,Del país,0,0,0,0,0,0,0,0,0,0,0,0,1525.3445,0,1525.3445,0,0,0,0.01,0,0,0,0,0,0,0.01,1525.3545,0,0.01,0,0,1525.3445
25,NaN,110510,Del exterior,0,0,0,155.07458,155.07458,0,52.797,0,0,0,0,9,0,0,61.797,0,0,0.408,0,0,0,0,0,0,0,0.408,217.27958,0,0,0,0,217.27958
26,NaN,12,OPERACIONES INTERBANCARIAS,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,NaN,1201,Fondos interbancarios vendidos,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,NaN,120105,Bancos,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,NaN,120110,Otras instituciones del sistema financiero,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,NaN,1202,Operaciones de reporto con instituciones finan...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31,NaN,120205,Instituciones financieras públicas,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32,NaN,120210,Bancos,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33,NaN,120215,Otras instituciones del sistema financiero,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
34,NaN,1299,(Provisión para operaciones interbancarias y d...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35,NaN,129905,(Provisión fondos interbancarios vendidos),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
36,NaN,129910,(Provisión para operaciones de reporto con ins...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
37,NaN,13,INVERSIONES,1860997.95365,2222512.48075,5545465.9726,1441204.31955,11070180.72655,674590.04705,1165732.61784,376281.729,299871.50529,236522.52289,859603.74982,147427.64882,184848.6882,73953.03415,4018831.54306,67787.96652,92891.86134,51273.97528,4929.75677,150264.73737,10400.05964,2596.82318,49773.53408,65313.05469,5808.84926,501040.61813,15590052.88774,1235885.47882,541323.78495,0,55582.38334,13757261.24063
38,NaN,1301,A valor razonable con cambios en el estado de ...,802.8081,0,0,0,802.8081,36000,0,0,0,0,281159.95676,0,0,0,317159.95676,0,0,0,0,0,0,0,0,0,0,0,317962.76486,281159.95676,0,0,0,36802.8081
39,NaN,130105,De 1 a 30 días,0,0,0,0,0,36000,0,0,0,0,101925.58904,0,0,0,137925.58904,0,0,0,0,0,0,0,0,0,0,0,137925.58904,101925.58904,0,0,0,36000
40,NaN,130110,De 31 a 90 días,592.05556,0,0,0,592.05556,0,0,0,0,0,179234.36772,0,0,0,179234.36772,0,0,0,0,0,0,0,0,0,0,0,179826.42328,179234.36772,0,0,0,592.05556
41,NaN,130115,De 91 a 180 días,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42,NaN,130120,De 181 A 360 días,210.75254,0,0,0,210.75254,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,210.75254,0,0,0,0,210.75254
43,NaN,130125,De más de 360 días,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44,NaN,1302,A valor razonable con cambios en el estado de ...,162305.95483,0,0,0,162305.95483,0,0,96022.214,0,0,33857.95735,0,0,0,129880.17135,0,0,0,0,0,0,0,0,0,0,0,292186.12618,129880.17135,0,0,0,162305.95483
45,NaN,130205,De 1 a 30 días,73620.65378,0,0,0,73620.65378,0,0,334.971,0,0,20550,0,0,0,20884.971,0,0,0,0,0,0,0,0,0,0,0,94505.62478,20884.971,0,0,0,73620.65378
46,NaN,130210,De 31 a 90 días,39850.70859,0,0,0,39850.70859,0,0,85034.209,0,0,13307.95735,0,0,0,98342.16635,0,0,0,0,0,0,0,0,0,0,0,138192.87494,98342.16635,0,0,0,39850.70859
47,NaN,130215,De 91 a 180 días,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
48,NaN,130220,De 181 A 360 días,48834.59246,0,0,0,48834.59246,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,48834.59246,0,0,0,0,48834.59246
49,NaN,130225,De más de 360 días,0,0,0,0,0,0,0,10653.034,0,0,0,0,0,0,10653.034,0,0,0,0,0,0,0,0,0,0,0,10653.034,10653.034,0,0,0,0
50,NaN,1303,Disponibles para la venta de entidades del sec...,130046.80768,462813.54507,714422.73629,694689.96651,2001973.05555,191194.19219,145243.93044,99923.41,7289.7676,65108.80599,106106.44665,71469.61649,20196.80906,37716.66887,744249.64729,1517.69767,46581.87389,15654.80647,1200,130684.61715,3667.28011,0,23532.22431,25576.45066,0,248414.95026,2994637.6531,206029.85665,73598.57359,0,23532.22431,2691476.99855
51,NaN,130305,De 1 a 30 días,54923.17917,99581.02427,39553.83681,385766.35734,579824.39759,38132.58873,60185.51731,59923.41,612.20177,8478.22916,33013.54546,35787.31739,0,8499.96156,244632.77138,0,32591.40276,14917.52615,1000,102777.13789,2217.11275,0,7797.68393,21372.43541,0,182673.29889,1007130.46786,92936.95546,10090.43093,0,7797.68393,896305.39754
52,NaN,130310,De 31 a 90 días,392.78779,45736.72902,42981.69316,294136.35936,383247.56933,29302.65275,21489.501,40000,330.03282,3080.11177,12053.29731,24046.55064,20000,19501.85391,169804.0002,1517.69767,10568.11874,140.50506,200,27890.54351,1450.16736,0,3180.08842,2747.39485,0,47694.51561,600746.08514,52053.29731,3610.14459,0,3180.08842,541902.55482
53,NaN,130315,De 91 a 180 días,16968.9617,92188.67169,100010.18917,5710.54092,214878.36348,49428.0248,15954.29386,0,149.36514,604.77321,18946.30095,11635.74846,0,9003.88607,105722.39249,0,2706.62433,596.77526,0,15.70668,0,0,1733.74376,911.8309,0,5964.68093,326565.4369,18946.30095,754.13835,0,1733.74376,305131.25384
54,NaN,130320,De 181 A 360 días,56660.64243,107917.56384,26600.94065,679.82069,191858.96761,30864.35322,17989.556,0,5301.97693,1125.02855,34449.94878,0,196.80906,710.96733,90638.63987,0,574.33977,0,0,0,0,0,2669.52334,544.7895,0,3788.65261,286286.26009,34449.94878,6427.00548,0,2669.52334,242739.78249
55,NaN,130325,De más de 360 días,1101.23659,117389.55625,505276.0765,8396.8882,632163.75754,43466.57269,29625.06227,0,896.19094,51820.6633,7643.35415,0,0,0,133451.84335,0,141.38829,0,0,1.22907,0,0,8151.18486,0,0,8293.80222,773909.40311,7643.35415,52716.85424,0,8151.18486,705398.00986
56,NaN,1304,Disponibles para la venta del Estado o de enti...,1070381.95122,826697.36397,3327044.00069,272048.12035,5496171.43623,230112.83854,682315.10047,143635.426,143826.24755,94231.07935,167527.12813,35403.3776,34040.63505,12796.86299,1543888.69568,21945.93764,16690.25051,7714.60562,1883.71829,9820,2299.81829,956.36936,19700.74714,9548.54477,2813.19016,93373.18178,7133433.31369,311162.55413,239941.04519,0,22513.9373,6559815.77707
57,NaN,130405,De 1 a 30 días,600,165864.11369,636995.18042,48676.47167,852135.76578,3541.29356,114449.53397,10569.789,52850.65202,36827.14466,21250,4514.42342,11750.26245,1982.32356,257735.42264,14964.65791,6002.96256,0,394.03901,890,1372.26001,103.91813,200,399.98301,0,24327.82063,1134199.00905,31819.789,90071.83569,0,200,1012107.38436
58,NaN,130410,De 31 a 90 días,132720.63731,168628.83644,666576.90948,19141.86938,987068.25261,18235.78535,54802.91583,7700,21670.05913,27506.71703,32000,6519.0248,2700.21286,7313.84752,178448.56252,6981.27973,8769.90784,250,196.02601,8930,927.55828,198.96756,0,1299.76411,1595.71485,29149.21838,1194666.03351,39700,49372.80217,0,1595.71485,1103997.51649
59,NaN,130415,De 91 a 180 días,89998.87595,215042.22964,970395.44829,31133.72987,1306570.28375,44948.16576,192480.7363,0,24074.55743,13324.32569,1625,10537.64003,12544.09638,3500.69191,303035.2135,0,444.01358,1550,1243.25967,0,0,280,400,1619.50124,1217.47531,6754.2498,1616359.74705,1625,38642.14279,0,1617.47531,1574475.12895
60,NaN,130420,De 181 A 360 días,290465.2524,113155.78433,647718.41547,107226.54359,1158565.99579,2088.16562,194694.11347,13156.587,4538.69483,4507.72728,0,13832.28935,7046.06336,0,239863.64091,0,116.79699,0,0,0,0,373.48367,2668.84707,5228.6811,0,8387.80883,1406817.44553,13156.587,9046.42211,0,2668.84707,1381945.58935
61,NaN,130425,De más de 360 días,556597.18556,164006.39987,405358.04703,65869.50584,1191831.1383,161299.42825,125887.8009,112209.05,40692.28414,12065.16469,112652.12813,0,0,0,564805.85611,0,1356.56954,5914.60562,50.3936,0,0,0,16431.90007,1000.61531,0,24754.08414,1781391.07855,224861.17813,52807.84243,0,16431.90007,1487290.15792
62,NaN,130430,Certificados de abono tributario,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
63,NaN,1305,Mantenidas hasta el vencimiento de entidades d...,24700,0,71242.58783,1556.08422,97498.67205,0,0,0,0,0,0,0,0,0,0,0,0,22453.87737,0,0,0,0,0,18651.46382,0,41105.34119,138604.01324,0,0,0,0,138604.01324
64,NaN,130505,De 1 a 30 días,0,0,25581.86285,73.97447,25655.83732,0,0,0,0,0,0,0,0,0,0,0,0,687.11342,0,0,0,0,0,8507.26841,0,9194.38183,34850.21915,0,0,0,0,34850.21915
65,NaN,130510,De 31 a 90 días,0,0,40524.36592,1363.69751,41888.06343,0,0,0,0,0,0,0,0,0,0,0,0,1506.25243,0,0,0,0,0,4872.75115,0,6379.00358,48267.06701,0,0,0,0,48267.06701
66,NaN,130515,De 91 a 180 días,0,0,4403.70147,118.41224,4522.11371,0,0,0,0,0,0,0,0,0,0,0,0,2899.94519,0,0,0,0,0,4382.62522,0,7282.57041,11804.68412,0,0,0,0,11804.68412
67,NaN,130520,De 181 días a 1 año,0,0,732.65759,0,732.65759,0,0,0,0,0,0,0,0,0,0,0,0,12179.248,0,0,0,0,0,888.81904,0,13068.06704,13800.72463,0,0,0,0,13800.72463
68,NaN,130525,De 1 a 3 años,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5181.31833,0,0,0,0,0,0,0,5181.31833,5181.31833,0,0,0,0,5181.31833
69,NaN,130530,De 3 a 5 años,24700,0,0,0,24700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24700,0,0,0,0,24700
70,NaN,130535,De 5 a 10 años,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
71,NaN,130540,De más de 10 años,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
72,NaN,1306,Mantenidas hasta su vencimiento del Estado o d...,370356.5824,344191.93585,837056.23171,336606.87329,1888211.62325,138221.67948,228484.63536,36700.679,89751.54773,57392.2348,231663.05652,40459.65473,120667.29019,23439.50229,966780.2801,42709.3055,26821.43029,5034.75817,1846.03848,9760.12022,3717.985,892.95382,4603.10517,11536.59544,2685.2971,109607.58919,2964599.49254,268363.73552,148989.82101,0,7288.40227,2539957.53374
73,NaN,130605,De 1 a 30 días,0,0,0,0,0,0,0,0,0,0,0,0,23809.38409,0,23809.38409,0,0,0,0,0,0,0,0,0,0,0,23809.38409,0,0,0,0,23809.38409
74,NaN,130610,De 31 a 90 días,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75,NaN,130615,De 91 a 180 días,370356.5824,344191.93585,837056.23171,336606.87329,1888211.62325,138221.67948,228484.63536,36700.679,89751.54773,57392.2348,231663.05652,40459.65473,51844.36561,23439.50229,897957.35552,28566.3509,17327.71499,5034.75817,1846.03848,9760.12022,3717.985,892.95382,4603.10517,11536.59544,2685.2971,85970.91929,2872139.89806,268363.73552,148989.82101,0,7288.40227,2447497.93926
76,NaN,130620,De 181 días a 1 año,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,79.2244,0,0,0,0,0,0,0,0,79.2244,79.2244,0,0,0,0,79.2244
77,NaN,130625,De 1 a 3 años,0,0,0,0,0,0,0,0,0,0,0,0,3387.89382,0,3387.89382,4975.1525,9414.4909,0,0,0,0,0,0,0,0,14389.6434,17777.53722,0,0,0,0,17777.53722
78,NaN,130630,De 3 a 5 años,0,0,0,0,0,0,0,0,0,0,0,0,35264.77022,0,35264.77022,9136.9746,0,0,0,0,0,0,0,0,0,9136.9746,44401.74482,0,0,0,0,44401.74482
79,NaN,130635,De 5 a 10 años,0,0,0,0,0,0,0,0,0,0,0,0,6360.87645,0,6360.87645,30.8275,0,0,0,0,0,0,0,0,0,30.8275,6391.70395,0,0,0,0,6391.70395

In [ ]:
# A partir de la exploración visual del archivo, identificamos que los nombres 
# de los bancos están en la fila 7 y los valores de los activos en la fila 9,
# comenzando desde la columna 3. Con esta información, podemos extraer los datos
# relevantes para crear una tabla de activos por banco.

fila_bancos = 7
fila_activos = 9
col_inicio_bancos = 3

bancos = df.iloc[fila_bancos, col_inicio_bancos:]
valores = df.iloc[fila_activos, col_inicio_bancos:]

tabla_activos = pd.DataFrame({
    "banco": bancos.values,
    "indicador": "Activos",
    "valor": valores.values
})

tabla_activos

                                                banco indicador          valor
0                                        BP GUAYAQUIL   Activos   962844.36003
1                                         BP PACIFICO   Activos    774077.6831
2                                        BP PICHINCHA   Activos  1913012.73986
3                                       BP PRODUBANCO   Activos  1021324.78103
4                             BANCOS PRIVADOS GRANDES   Activos  4671259.56402
5                                           BP AUSTRO   Activos   530918.75278
6                                      BP BOLIVARIANO   Activos   580471.74464
7                                         BP CITIBANK   Activos     154087.561
8                                           BP DINERS   Activos   167846.30716
9                                BP GENERAL RUMIÑAHUI   Activos   208702.64099
10                                   BP INTERNACIONAL   Activos   740954.91881
11                                            BP LOJA   Activos    215386.4228
12                                         BP MACHALA   Activos   202028.38329
13                                       BP SOLIDARIO   Activos    74290.21813
14                           BANCOS PRIVADOS MEDIANOS   Activos   2874686.9496
15                                       BP PROCREDIT   Activos    81402.32482
16                                        BP AMAZONAS   Activos    62943.14724
17                       BP BANCO COMERCIAL DE MANABI   Activos     16815.9418
18                                         BP LITORAL   Activos     3962.93017
19                                    BP COOPNACIONAL   Activos    57257.35337
20                                         BP CAPITAL   Activos     7346.76897
21                                         BP DELBANK   Activos     8241.76457
22                               BANCO ATLÁNTIDA S.A.   Activos    15625.79264
23  BP BANCO  DESARROLLO DE LOS PUEBLOS  S.A., COD...   Activos    42802.81765
24                         BP VISIONFUND ECUADOR S.A.   Activos    11688.15365
25                           BANCOS PRIVADOS PEQUEÑOS   Activos   308086.99488
26                              TOTAL BANCOS PRIVADOS   Activos   7854033.5085
27                        BANCOS PRIVADOS COMERCIALES   Activos   895042.47981
28                            BANCOS PRIVADOS CONSUMO   Activos   380511.87832
29                           BANCOS PRIVADOS VIVIENDA   Activos              0
30                       BANCOS PRIVADOS MICROCRÉDITO   Activos    27313.94629
31                                     BANCA MÚLTIPLE   Activos  6551165.20408

In [ ]:
# Limpiamos la tabla eliminando filas con valores
# nulos en la columna "banco" y formateando los datos
tabla_activos = tabla_activos.dropna(subset=["banco"])

tabla_activos["banco"] = (
    tabla_activos["banco"]
    .astype(str)
    .str.strip()
    .str.upper()
)

tabla_activos["valor"] = (
    tabla_activos["valor"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace(" ", "", regex=False)
)

tabla_activos["valor"] = pd.to_numeric(tabla_activos["valor"], errors="coerce").round(2)

#Controla la visualización de los números en la tabla para que se muestren con formato de miles y dos decimales
pd.set_option("display.float_format", "{:,.2f}".format)

tabla_activos

,banco,indicador,valor,periodo,archivo_origen
0,BP GUAYAQUIL,Activos,"962,844.36",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
1,BP PACIFICO,Activos,"774,077.68",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
2,BP PICHINCHA,Activos,"1,913,012.74",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
3,BP PRODUBANCO,Activos,"1,021,324.78",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
4,BANCOS PRIVADOS GRANDES,Activos,"4,671,259.56",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
5,BP AUSTRO,Activos,"530,918.75",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
6,BP BOLIVARIANO,Activos,"580,471.74",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
7,BP CITIBANK,Activos,"154,087.56",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
8,BP DINERS,Activos,"167,846.31",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
9,BP GENERAL RUMIÑAHUI,Activos,"208,702.64",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
10,BP INTERNACIONAL,Activos,"740,954.92",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
11,BP LOJA,Activos,"215,386.42",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
12,BP MACHALA,Activos,"202,028.38",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
13,BP SOLIDARIO,Activos,"74,290.22",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
14,BANCOS PRIVADOS MEDIANOS,Activos,"2,874,686.95",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
15,BP PROCREDIT,Activos,"81,402.32",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
16,BP AMAZONAS,Activos,"62,943.15",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
17,BP BANCO COMERCIAL DE MANABI,Activos,"16,815.94",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
18,BP LITORAL,Activos,"3,962.93",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
19,BP COOPNACIONAL,Activos,"57,257.35",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
20,BP CAPITAL,Activos,"7,346.77",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
21,BP DELBANK,Activos,"8,241.76",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
22,BANCO ATLÁNTIDA S.A.,Activos,"15,625.79",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
23,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",Activos,"42,802.82",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
24,BP VISIONFUND ECUADOR S.A.,Activos,"11,688.15",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
25,BANCOS PRIVADOS PEQUEÑOS,Activos,"308,086.99",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
26,TOTAL BANCOS PRIVADOS,Activos,"7,854,033.51",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
27,BANCOS PRIVADOS COMERCIALES,Activos,"895,042.48",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
28,BANCOS PRIVADOS CONSUMO,Activos,"380,511.88",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
29,BANCOS PRIVADOS VIVIENDA,Activos,0.00,2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
30,BANCOS PRIVADOS MICROCRÉDITO,Activos,"27,313.95",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
31,BANCA MÚLTIPLE,Activos,"6,551,165.20",2024-01,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx

In [21]:
# A partir de la exploración visual del archivo, identificamos que la fecha del periodo 
# se encuentra en la cabecera del archivo, por lo que podemos crear una función para 
# extraer esa información y agregarla a nuestra tabla de activos por banco.
import re
import pandas as pd
from datetime import datetime

def normalizar_mes_espanol(fecha_str):
    meses = {
        "ENE": "JAN",
        "FEB": "FEB",
        "MAR": "MAR",
        "ABR": "APR",
        "MAY": "MAY",
        "JUN": "JUN",
        "JUL": "JUL",
        "AGO": "AUG",
        "SEP": "SEP",
        "OCT": "OCT",
        "NOV": "NOV",
        "DIC": "DEC"
    }

    fecha_str = fecha_str.upper().strip()

    for mes_es, mes_en in meses.items():
        fecha_str = fecha_str.replace(mes_es, mes_en)

    return fecha_str


def parsear_fecha(fecha_str):
    fecha_str = normalizar_mes_espanol(fecha_str)

    formatos = [
        "%d/%m/%Y",   # 28/02/2015
        "%Y-%m-%d",   # 2015-02-28
        "%d-%b-%Y",   # 28-FEB-2015
        "%d/%b/%Y",   # 28/FEB/2015
    ]

    for formato in formatos:
        try:
            return datetime.strptime(fecha_str, formato)
        except ValueError:
            continue

    return None


def obtener_periodo_desde_cabecera(archivo, sheet_name=0, filas_cabecera=15):
    df_header = pd.read_excel(
        archivo,
        sheet_name=sheet_name,
        header=None,
        nrows=filas_cabecera
    )

    patron_fecha = (
        r"\b\d{2}/\d{2}/\d{4}\b|"      # 28/02/2015
        r"\b\d{4}-\d{2}-\d{2}\b|"      # 2015-02-28
        r"\b\d{2}-[A-ZÁÉÍÓÚÑ]{3}-\d{4}\b|"  # 28-FEB-2015
        r"\b\d{2}/[A-ZÁÉÍÓÚÑ]{3}/\d{4}\b"   # 28/FEB/2015
    )

    for fila in range(df_header.shape[0]):
        for col in range(df_header.shape[1]):
            valor = str(df_header.iloc[fila, col]).strip().upper()

            match = re.search(patron_fecha, valor)

            if match:
                fecha = parsear_fecha(match.group())

                if fecha:
                    return fecha.strftime("%Y-%m")

    raise ValueError(f"No se encontró una fecha válida en la cabecera del archivo: {archivo}")

In [28]:
periodo = obtener_periodo_desde_cabecera(archivo)

tabla_activos["periodo"] = periodo

tabla_activos

,banco,indicador,valor,periodo
0,BP GUAYAQUIL,Activos,"962,844.36",2026-03
1,BP PACIFICO,Activos,"774,077.68",2026-03
2,BP PICHINCHA,Activos,"1,913,012.74",2026-03
3,BP PRODUBANCO,Activos,"1,021,324.78",2026-03
4,BANCOS PRIVADOS GRANDES,Activos,"4,671,259.56",2026-03
5,BP AUSTRO,Activos,"530,918.75",2026-03
6,BP BOLIVARIANO,Activos,"580,471.74",2026-03
7,BP CITIBANK,Activos,"154,087.56",2026-03
8,BP DINERS,Activos,"167,846.31",2026-03
9,BP GENERAL RUMIÑAHUI,Activos,"208,702.64",2026-03
10,BP INTERNACIONAL,Activos,"740,954.92",2026-03
11,BP LOJA,Activos,"215,386.42",2026-03
12,BP MACHALA,Activos,"202,028.38",2026-03
13,BP SOLIDARIO,Activos,"74,290.22",2026-03
14,BANCOS PRIVADOS MEDIANOS,Activos,"2,874,686.95",2026-03
15,BP PROCREDIT,Activos,"81,402.32",2026-03
16,BP AMAZONAS,Activos,"62,943.15",2026-03
17,BP BANCO COMERCIAL DE MANABI,Activos,"16,815.94",2026-03
18,BP LITORAL,Activos,"3,962.93",2026-03
19,BP COOPNACIONAL,Activos,"57,257.35",2026-03
20,BP CAPITAL,Activos,"7,346.77",2026-03
21,BP DELBANK,Activos,"8,241.76",2026-03
22,BANCO ATLÁNTIDA S.A.,Activos,"15,625.79",2026-03
23,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",Activos,"42,802.82",2026-03
24,BP VISIONFUND ECUADOR S.A.,Activos,"11,688.15",2026-03
25,BANCOS PRIVADOS PEQUEÑOS,Activos,"308,086.99",2026-03
26,TOTAL BANCOS PRIVADOS,Activos,"7,854,033.51",2026-03
27,BANCOS PRIVADOS COMERCIALES,Activos,"895,042.48",2026-03
28,BANCOS PRIVADOS CONSUMO,Activos,"380,511.88",2026-03
29,BANCOS PRIVADOS VIVIENDA,Activos,0.00,2026-03
30,BANCOS PRIVADOS MICROCRÉDITO,Activos,"27,313.95",2026-03
31,BANCA MÚLTIPLE,Activos,"6,551,165.20",2026-03

In [30]:
tabla_activos

,periodo,banco,indicador,valor
0,2026-03,BP GUAYAQUIL,Activos,"962,844.36"
1,2026-03,BP PACIFICO,Activos,"774,077.68"
2,2026-03,BP PICHINCHA,Activos,"1,913,012.74"
3,2026-03,BP PRODUBANCO,Activos,"1,021,324.78"
4,2026-03,BANCOS PRIVADOS GRANDES,Activos,"4,671,259.56"
5,2026-03,BP AUSTRO,Activos,"530,918.75"
6,2026-03,BP BOLIVARIANO,Activos,"580,471.74"
7,2026-03,BP CITIBANK,Activos,"154,087.56"
8,2026-03,BP DINERS,Activos,"167,846.31"
9,2026-03,BP GENERAL RUMIÑAHUI,Activos,"208,702.64"
10,2026-03,BP INTERNACIONAL,Activos,"740,954.92"
11,2026-03,BP LOJA,Activos,"215,386.42"
12,2026-03,BP MACHALA,Activos,"202,028.38"
13,2026-03,BP SOLIDARIO,Activos,"74,290.22"
14,2026-03,BANCOS PRIVADOS MEDIANOS,Activos,"2,874,686.95"
15,2026-03,BP PROCREDIT,Activos,"81,402.32"
16,2026-03,BP AMAZONAS,Activos,"62,943.15"
17,2026-03,BP BANCO COMERCIAL DE MANABI,Activos,"16,815.94"
18,2026-03,BP LITORAL,Activos,"3,962.93"
19,2026-03,BP COOPNACIONAL,Activos,"57,257.35"
20,2026-03,BP CAPITAL,Activos,"7,346.77"
21,2026-03,BP DELBANK,Activos,"8,241.76"
22,2026-03,BANCO ATLÁNTIDA S.A.,Activos,"15,625.79"
23,2026-03,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",Activos,"42,802.82"
24,2026-03,BP VISIONFUND ECUADOR S.A.,Activos,"11,688.15"
25,2026-03,BANCOS PRIVADOS PEQUEÑOS,Activos,"308,086.99"
26,2026-03,TOTAL BANCOS PRIVADOS,Activos,"7,854,033.51"
27,2026-03,BANCOS PRIVADOS COMERCIALES,Activos,"895,042.48"
28,2026-03,BANCOS PRIVADOS CONSUMO,Activos,"380,511.88"
29,2026-03,BANCOS PRIVADOS VIVIENDA,Activos,0.00
30,2026-03,BANCOS PRIVADOS MICROCRÉDITO,Activos,"27,313.95"
31,2026-03,BANCA MÚLTIPLE,Activos,"6,551,165.20"