In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

In [2]:
# Ruta base del proyecto
BASE_DIR = Path.cwd().parent

# Carpetas principales
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
OUTPUTS_DIR = DATA_DIR / "outputs"

print("BASE_DIR:", BASE_DIR)
print("RAW_DIR:", RAW_DIR)
print("PROCESSED_DIR:", PROCESSED_DIR)
print("OUTPUTS_DIR:", OUTPUTS_DIR)

BASE_DIR: c:\Users\Gladys\Documents\Eddy\Seminario Python\proyecto_bancos
RAW_DIR: c:\Users\Gladys\Documents\Eddy\Seminario Python\proyecto_bancos\data\raw
PROCESSED_DIR: c:\Users\Gladys\Documents\Eddy\Seminario Python\proyecto_bancos\data\processed
OUTPUTS_DIR: c:\Users\Gladys\Documents\Eddy\Seminario Python\proyecto_bancos\data\outputs

In [3]:
# Listar archivos Excel en la carpeta raw
archivos_excel = [
    archivo for archivo in RAW_DIR.iterdir()
    if archivo.suffix.lower() in [".xlsx", ".xls", ".xlsm"]
    and not archivo.name.startswith("~$")
]

archivos_excel

[WindowsPath('c:/Users/Gladys/Documents/Eddy/Seminario Python/proyecto_bancos/data/raw/BOL BANCOS PRIVADOS 28022015 act.xlsx'),
 WindowsPath('c:/Users/Gladys/Documents/Eddy/Seminario Python/proyecto_bancos/data/raw/BOL_BP_AGOSTO 2018.xlsx'),
 WindowsPath('c:/Users/Gladys/Documents/Eddy/Seminario Python/proyecto_bancos/data/raw/FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx')]

In [4]:
for i, archivo in enumerate(archivos_excel, start=1):
    print(i, archivo.name)

1 BOL BANCOS PRIVADOS 28022015 act.xlsx
2 BOL_BP_AGOSTO 2018.xlsx
3 FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx

In [7]:
archivos_piloto = [
    RAW_DIR / "BOL BANCOS PRIVADOS 28022015 act.xlsx",
    RAW_DIR / "FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx"
]

for archivo in archivos_piloto:
    print(archivo.exists(), archivo.name)

True BOL BANCOS PRIVADOS 28022015 act.xlsx
True FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx

In [8]:
# Explorar las hojas de los archivos piloto
for archivo in archivos_piloto:
    print("=" * 80)
    print("Archivo:", archivo.name)
    
    excel = pd.ExcelFile(archivo)
    
    for hoja in excel.sheet_names:
        print("-", hoja)

================================================================================
Archivo: BOL BANCOS PRIVADOS 28022015 act.xlsx
- BALANCE
- PYG
- CONSCOND
- BALCONS
- BALCONS %
- RK
- GRAFICOS RK
- COMPOS CART
- COMPOS CART %
- EPyG
- EPyG %
- INDICADORES
- CART X PLAZOS
================================================================================
Archivo: FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
- BALANCE
- PYG
- BALANCE %
- EPyG %
- CONSCOND
- RK
- Gráficos RK
- COMPOS CART
- COMPOS CART %
- MET
- INDICADORES
- REP GERENCIAL

In [ ]:
# Paso 7: Verificar si las hojas clave existen en los archivos piloto
hojas_requeridas = ["BALANCE", "INDICADORES"]

for archivo in archivos_piloto:
    excel = pd.ExcelFile(archivo)
    hojas_disponibles = excel.sheet_names
    
    print("=" * 80)
    print("Archivo:", archivo.name)
    
    for hoja in hojas_requeridas:
        if hoja in hojas_disponibles:
            print(f"✅ Existe hoja: {hoja}")
        else:
            print(f"❌ No existe hoja: {hoja}")

================================================================================
Archivo: BOL BANCOS PRIVADOS 28022015 act.xlsx
✅ Existe hoja: BALANCE
✅ Existe hoja: INDICADORES
================================================================================
Archivo: FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
✅ Existe hoja: BALANCE
✅ Existe hoja: INDICADORES

In [ ]:
# Paso 8: Leer las hojas clave y mostrar un preview de Balance
for archivo in archivos_piloto:
    print("=" * 100)
    print("Archivo:", archivo.name)
    
    try:
        df_preview = pd.read_excel(
            archivo,
            sheet_name="BALANCE",
            header=None,
            nrows=15
        )
        
        display(df_preview)
        
    except Exception as e:
        print("Error leyendo BALANCE:", e)

====================================================================================================
Archivo: BOL BANCOS PRIVADOS 28022015 act.xlsx

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,ESTADO DE SITUACIÓN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2015-02-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,2,1,2,3,4,5,6,7,...,22,23,24,25,26,27,28,29,30,31
6,1.0,CODIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BP FINCA,BP DELBANK,BP D-MIRO S.A.,BP BANCODESARROLLO,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS DE MICROEMPRESA
7,2.0,1,ACTIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,3.0,11,FONDOS DISPONIBLES,765311.7013,466034.05389,820165.50751,671361.2107,2722872.4734,243769.25804,612752.91782,...,3055.24129,4691.78577,2136.09632,7091.82753,118244.3528,4773927.88563,3788233.22631,869536.13263,NaN,116158.52669
9,4.0,1101,Caja,103729.4385,152010.97743,323965.81755,102352.834,682059.06748,45190.57274,103743.5225,...,546.45064,1945.1128,817.71388,2522.42189,16514.37845,986284.72882,752406.26831,214395.39963,NaN,19483.06088
10,5.0,110105,Efectivo,103729.4385,152010.78743,323943.92614,102352.834,682036.98607,45188.82274,103743.52179,...,542.25064,1941.9628,817.71388,2518.84189,16481.42519,986197.78844,752367.19119,214390.93637,NaN,19439.66088
11,6.0,110110,Caja chica,0,0.19,21.89141,0,22.08141,1.75,0.00071,...,4.2,3.15,0,3.58,32.95326,86.94038,39.07712,4.46326,NaN,43.4
12,7.0,1102,Depósitos para encaje,196927.25458,220400.02853,231945.71841,251117.2684,900390.26992,69325.18994,80462.18755,...,330.91899,300.72844,410.8485,2307.38727,29234.32945,1457519.10464,1109757.993,321986.67599,NaN,25774.43565
13,8.0,110205,Banco Central del Ecuador,196837.87516,220400.02853,231945.71841,251117.2684,900300.8905,69123.43094,80462.18755,...,330.91899,300.72844,410.8485,2307.38727,29132.98262,1457068.52947,1109610.52366,321683.57016,NaN,25774.43565
14,9.0,110210,Banco Nacional de Fomento,13.18103,0,0,0,13.18103,201.759,0,...,0,0,0,0,101.34683,374.37678,71.27095,303.10583,NaN,0

====================================================================================================
Archivo: FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,ESTADO DE SITUACIÓN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,7854033.5085,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,CÓDIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE,NaN
8,NaN,NaN,ACTIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,11,FONDOS DISPONIBLES,962844.36003,774077.6831,1913012.73986,1021324.78103,4671259.56402,530918.75278,580471.74464,...,42802.81765,11688.15365,308086.99488,7854033.5085,895042.47981,380511.87832,0,27313.94629,6551165.20408,1.302868e+06
10,NaN,1101,Caja,202958.75959,276232.61409,321160.33829,92656.11901,893007.83098,89082.34343,125314.40563,...,5211.29962,1832.63559,27061.76074,1303829.79611,81120.62946,16218.79754,0,2706.31004,1203784.05907,NaN
11,NaN,110105,Efectivo,202958.75959,276232.61409,321104.63829,92656.11901,892952.13098,89081.74343,125314.40563,...,5205.69962,1819.43559,27024.86964,1303705.13535,81112.49946,16214.85644,0,2693.11004,1203684.66941,NaN
12,NaN,110110,Caja chica,0,0,55.7,0,55.7,0.6,0,...,5.6,13.2,36.8911,124.66076,8.13,3.9411,0,13.2,99.38966,NaN
13,NaN,1102,Depósitos para encaje,304412.00314,384760.1572,685536.21093,330346.65553,1705055.0268,156029.0075,163538.45422,...,17947.60075,3848.43766,111541.50726,2878840.56762,431451.86148,144549.60466,0,10466.65062,2292372.45086,NaN
14,NaN,110205,Banco Central del Ecuador,304411.8188,384760.1572,685536.21093,330346.65553,1705054.84246,156029.0075,163538.45422,...,17947.60075,3848.43766,111541.50726,2878839.38328,431451.86148,144549.60466,0,10466.65062,2292371.26652,NaN

In [11]:
# Paso 8: Leer las hojas clave y mostrar un preview de Indicadores
for archivo in archivos_piloto:
    print("=" * 100)
    print("Archivo:", archivo.name)
    
    try:
        df_preview = pd.read_excel(
            archivo,
            sheet_name="INDICADORES",
            header=None,
            nrows=15
        )
        
        display(df_preview)
        
    except Exception as e:
        print("Error leyendo INDICADORES:", e)

====================================================================================================
Archivo: BOL BANCOS PRIVADOS 28022015 act.xlsx

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,INDICADORES FINANCIEROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,2015-02-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,(en porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.0,COD. MAF.,NOMBRE DEL INDICADOR,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,...,BP FINCA,BP DELBANK,BP D-MIRO S.A.,BP BANCODESARROLLO,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS DE MICROEMPRESA
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,SUFICIENCIA PATRIMONIAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,IF114,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILI...,172.086857,351.568821,2123.152731,241.163175,387.824769,166.889954,271.104736,...,283.85339,351.858869,357.28573,219.917,188.431948,354.961999,383.372697,290.69245,NaN,358.612138
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,ESTRUCTURA Y CALIDAD DE ACTIVOS:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,IF102,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,14.835586,12.408004,8.017489,13.029679,11.031858,13.740806,12.113119,...,8.028728,19.525578,5.647269,9.144026,13.173429,11.499781,11.42912,12.300164,NaN,8.220237
14,NaN,IF101,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,85.164414,87.591996,91.982511,86.970321,88.968142,86.259194,87.886881,...,91.971272,80.474422,94.352731,90.855974,86.826571,88.500219,88.57088,87.699836,NaN,91.779763

====================================================================================================
Archivo: FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,INDICADORES FINANCIEROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,31/03/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,(En porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NOMBRE DEL INDICADOR,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO,BP CITIBANK,...,BANCO ATLÁNTIDA S.A.,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",BP VISIONFUND ECUADOR S.A.,BANCOS PRIVADOS PEQUEÑOS,TOTAL BANCOS PRIVADOS,BANCOS PRIVADOS COMERCIALES,BANCOS PRIVADOS CONSUMO,BANCOS PRIVADOS VIVIENDA,BANCOS PRIVADOS MICROCRÉDITO,BANCA MÚLTIPLE
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,SUFICIENCIA PATRIMONIAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILI...,2.431012,4.088927,34.881393,3.481837,5.392486,0.828583,3.883123,-48.596892,...,0.924906,2.556251,23.291996,1.914036,4.144089,7.588859,3.764319,0,2.69822,4.011342
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,ESTRUCTURA Y CALIDAD DE ACTIVOS:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,0.087592,0.094119,0.049942,0.073313,0.070254,0.172191,0.075263,0.096769,...,0.135222,0.116259,0.038628,0.118368,0.079453,0.08873,0.074656,0,0.08307,0.078799
14,NaN,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,0.912408,0.905881,0.950058,0.926687,0.929746,0.827809,0.924737,0.903231,...,0.864778,0.883741,0.961372,0.881632,0.920547,0.91127,0.925344,0,0.91693,0.921201

Iniciamos el proceso de limpieza para obtener el periodo de todos los archivos

In [12]:
import re
import unicodedata
from datetime import datetime

In [14]:
# Función para normalizar texto
def normalizar_texto(texto):
    """
    Convierte texto a mayúsculas, elimina tildes,
    espacios dobles y caracteres innecesarios.
    """
    if pd.isna(texto):
        return ""
    
    texto = str(texto).strip().upper()
    
    # Eliminar tildes
    texto = unicodedata.normalize("NFKD", texto)
    texto = "".join(c for c in texto if not unicodedata.combining(c))
    
    # Normalizar espacios
    texto = re.sub(r"\s+", " ", texto)
    
    return texto.strip()


MESES = {
    "ENE": "01", "ENERO": "01", "JAN": "01", "JANUARY": "01",
    "FEB": "02", "FEBRERO": "02", "FEBRUARY": "02",
    "MAR": "03", "MARZO": "03", "MARCH": "03",
    "ABR": "04", "ABRIL": "04", "APR": "04", "APRIL": "04",
    "MAY": "05", "MAYO": "05",
    "JUN": "06", "JUNIO": "06", "JUNE": "06",
    "JUL": "07", "JULIO": "07", "JULY": "07",
    "AGO": "08", "AGOSTO": "08", "AUG": "08", "AUGUST": "08",
    "SEP": "09", "SEPT": "09", "SEPTIEMBRE": "09", "SEPTEMBER": "09",
    "OCT": "10", "OCTUBRE": "10", "OCTOBER": "10",
    "NOV": "11", "NOVIEMBRE": "11", "NOVEMBER": "11",
    "DIC": "12", "DICIEMBRE": "12", "DEC": "12", "DECEMBER": "12",
}

In [15]:
# Función para extraer periodo desde texto
def extraer_periodo_desde_texto(texto):
    """
    Extrae una fecha desde un texto y devuelve periodo en formato YYYY-MM.
    Soporta formatos como:
    - 28-FEB-2015
    - 28/02/2015
    - 2015-02-28
    - 31 DE MARZO DE 2026
    """
    
    texto_norm = normalizar_texto(texto)
    
    # Caso 1: formato YYYY-MM-DD o YYYY/MM/DD
    patron_yyyy_mm_dd = r"(\d{4})[-/](\d{1,2})[-/](\d{1,2})"
    match = re.search(patron_yyyy_mm_dd, texto_norm)
    
    if match:
        anio = match.group(1)
        mes = match.group(2).zfill(2)
        return f"{anio}-{mes}"
    
    # Caso 2: formato DD/MM/YYYY o DD-MM-YYYY
    patron_dd_mm_yyyy = r"(\d{1,2})[-/](\d{1,2})[-/](\d{4})"
    match = re.search(patron_dd_mm_yyyy, texto_norm)
    
    if match:
        mes = match.group(2).zfill(2)
        anio = match.group(3)
        return f"{anio}-{mes}"
    
    # Caso 3: formato DD-MES-YYYY o DD MES YYYY
    patron_dd_mes_yyyy = r"(\d{1,2})[-\s]+([A-Z]+)[-\s]+(\d{4})"
    match = re.search(patron_dd_mes_yyyy, texto_norm)
    
    if match:
        mes_texto = match.group(2)
        anio = match.group(3)
        
        if mes_texto in MESES:
            mes = MESES[mes_texto]
            return f"{anio}-{mes}"
    
    # Caso 4: formato DD DE MES DE YYYY
    patron_dd_de_mes_de_yyyy = r"(\d{1,2})\s+DE\s+([A-Z]+)\s+DE\s+(\d{4})"
    match = re.search(patron_dd_de_mes_de_yyyy, texto_norm)
    
    if match:
        mes_texto = match.group(2)
        anio = match.group(3)
        
        if mes_texto in MESES:
            mes = MESES[mes_texto]
            return f"{anio}-{mes}"
    
    return None

In [ ]:
# Función para extraer periodo desde un archivo Excel
def extraer_periodo_archivo(archivo, hojas_busqueda=None, max_filas=20, max_columnas=10):
    """
    Busca la fecha del boletín en las primeras filas y columnas del archivo.
    Primero intenta en BALANCE e INDICADORES.
    Si no encuentra, intenta extraer desde el nombre del archivo.
    """
    
    if hojas_busqueda is None:
        hojas_busqueda = ["BALANCE", "INDICADORES"]
    
    excel = pd.ExcelFile(archivo)
    
    for hoja in hojas_busqueda:
        if hoja not in excel.sheet_names:
            continue
        
        df_header = pd.read_excel(
            archivo,
            sheet_name=hoja,
            header=None,
            nrows=max_filas,
            usecols=range(max_columnas)
        )
        
        textos = []
        
        for valor in df_header.values.flatten():
            if pd.notna(valor):
                textos.append(str(valor))
        
        texto_completo = " ".join(textos)
        periodo = extraer_periodo_desde_texto(texto_completo)
        
        if periodo:
            return periodo
    
    # Fallback: intentar desde el nombre del archivo
    periodo_nombre = extraer_periodo_desde_texto(archivo.name)
    
    if periodo_nombre:
        return periodo_nombre
    
    return None

In [17]:
# Extraer periodo de los archivos piloto
for archivo in archivos_piloto:
    periodo = extraer_periodo_archivo(archivo)
    print(archivo.name, "=>", periodo)

BOL BANCOS PRIVADOS 28022015 act.xlsx => 2015-02
FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx => 2026-03

In [26]:
# Definir categorías agregadas que no corresponden a bancos individuales
CATEGORIAS_EXCLUIR = [
    "BANCOS PRIVADOS GRANDES",
    "BANCOS PRIVADOS MEDIANOS",
    "BANCOS PRIVADOS PEQUENOS",
    "BANCOS PRIVADOS PEQUEÑOS",
    "TOTAL BANCOS PRIVADOS",
    "BANCOS PRIVADOS COMERCIALES",
    "BANCOS PRIVADOS CONSUMO",
    "BANCOS PRIVADOS VIVIENDA",
    "BANCOS PRIVADOS MICROCREDITO",
    "BANCOS PRIVADOS MICROCRÉDITO",
    "BANCA MULTIPLE",
    "BANCA MÚLTIPLE",
    "BANCOS PRIVADOS DE MICROEMPRESA"
]


def es_categoria_agregada(nombre):
    """
    Retorna True si el nombre corresponde a una categoría agregada
    y no a un banco individual.
    """
    nombre_norm = normalizar_texto(nombre)
    
    for categoria in CATEGORIAS_EXCLUIR:
        categoria_norm = normalizar_texto(categoria)
        
        if categoria_norm in nombre_norm:
            return True
    
    return False

In [27]:
# Lista de palabras clave que suelen aparecer en nombres de bancos
PALABRAS_CLAVE_BANCOS = [
    "PICHINCHA",
    "GUAYAQUIL",
    "PACIFICO",
    "PACÍFICO",
    "PRODUBANCO",
    "AUSTRO",
    "BOLIVARIANO",
    "CITIBANK",
    "DINERS",
    "RUMINAHUI",
    "RUMIÑAHUI",
    "INTERNACIONAL",
    "LOJA",
    "MACHALA",
    "SOLIDARIO",
    "PROCREDIT",
    "AMAZONAS",
    "COMERCIAL DE MANABI",
    "COMERCIAL DE MANABÍ",
    "LITORAL",
    "COOPNACIONAL",
    "CAPITAL",
    "DELBANK",
    "ATLANTIDA",
    "ATLÁNTIDA",
    "CODESARROLLO",
    "VISIONFUND",
    "BANCO",
    "BP"
]


def parece_banco(nombre):
    """
    Evalúa si un texto parece ser un banco individual.
    """
    nombre_norm = normalizar_texto(nombre)
    
    if not nombre_norm:
        return False
    
    # Excluir categorías agregadas
    if es_categoria_agregada(nombre_norm):
        return False
    
    # Excluir textos administrativos
    textos_no_bancos = [
        "CODIGO",
        "CÓDIGO",
        "CUENTA",
        "DESCRIPCION",
        "DESCRIPCIÓN",
        "FECHA",
        "SALDO",
        "TOTAL ACTIVO",
        "TOTAL PASIVO",
        "PATRIMONIO"
    ]
    
    for texto in textos_no_bancos:
        if normalizar_texto(texto) == nombre_norm:
            return False
    
    # Si contiene palabras típicas de bancos
    for palabra in PALABRAS_CLAVE_BANCOS:
        if normalizar_texto(palabra) in nombre_norm:
            return True
    
    return False


def detectar_fila_bancos(archivo, hoja, max_filas=20):
    """
    Detecta automáticamente la fila donde están los nombres de bancos.
    Retorna el índice de fila en base 0.
    """
    
    df = pd.read_excel(
        archivo,
        sheet_name=hoja,
        header=None,
        nrows=max_filas
    )
    
    mejor_fila = None
    mejor_conteo = 0
    
    for idx, fila in df.iterrows():
        conteo_bancos = 0
        
        for valor in fila:
            if parece_banco(valor):
                conteo_bancos += 1
        
        if conteo_bancos > mejor_conteo:
            mejor_conteo = conteo_bancos
            mejor_fila = idx
    
    if mejor_fila is None or mejor_conteo < 3:
        return None
    
    return mejor_fila

In [28]:
# Función para extraer bancos por hoja
def extraer_bancos_hoja(archivo, hoja):
    """
    Extrae los bancos reales de una hoja determinada.
    Devuelve un DataFrame con:
    - archivo
    - hoja
    - fila_excel
    - columna_excel
    - banco_original
    """
    
    fila_bancos = detectar_fila_bancos(archivo, hoja)
    
    if fila_bancos is None:
        return pd.DataFrame()
    
    df = pd.read_excel(
        archivo,
        sheet_name=hoja,
        header=None
    )
    
    fila = df.iloc[fila_bancos]
    
    bancos = []
    
    for col_idx, valor in fila.items():
        if pd.isna(valor):
            continue
        
        nombre = str(valor).strip()
        
        if parece_banco(nombre):
            bancos.append({
                "archivo": archivo.name,
                "hoja": hoja,
                "fila_excel": fila_bancos + 1,
                "columna_excel_num": col_idx + 1,
                "banco_original": nombre,
                "banco_normalizado_preliminar": normalizar_texto(nombre)
            })
    
    return pd.DataFrame(bancos)

In [29]:
# Resumen de bancos detectados por archivo y hoja
bancos_detectados = []

for archivo in archivos_piloto:
    for hoja in ["BALANCE", "INDICADORES"]:
        df_bancos = extraer_bancos_hoja(archivo, hoja)
        bancos_detectados.append(df_bancos)

df_bancos_detectados = pd.concat(bancos_detectados, ignore_index=True)

df_bancos_detectados

,archivo,hoja,fila_excel,columna_excel_num,banco_original,banco_normalizado_preliminar
0,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,7,4,BP GUAYAQUIL,BP GUAYAQUIL
1,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,7,5,BP PACIFICO,BP PACIFICO
2,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,7,6,BP PICHINCHA,BP PICHINCHA
3,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,7,7,BP PRODUBANCO,BP PRODUBANCO
4,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,7,9,BP AUSTRO,BP AUSTRO
...,...,...,...,...,...,...
87,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,INDICADORES,8,23,BP CAPITAL,BP CAPITAL
88,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,INDICADORES,8,24,BP DELBANK,BP DELBANK
89,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,INDICADORES,8,25,BANCO ATLÁNTIDA S.A.,BANCO ATLANTIDA S.A.
90,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,INDICADORES,8,26,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...","BP BANCO DESARROLLO DE LOS PUEBLOS S.A., CODES..."
91,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,INDICADORES,8,27,BP VISIONFUND ECUADOR S.A.,BP VISIONFUND ECUADOR S.A.

In [30]:
# Resumen de bancos detectados por archivo y hoja
df_bancos_detectados.groupby(["archivo", "hoja"]).agg(
    cantidad_bancos=("banco_original", "count"),
    fila_excel=("fila_excel", "first")
).reset_index()

,archivo,hoja,cantidad_bancos,fila_excel
0,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,23,7
1,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,23,8
2,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,BALANCE,23,8
3,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,INDICADORES,23,8

In [31]:
# Mostrar bancos detectados por archivo y hoja
for archivo in archivos_piloto:
    print("=" * 100)
    print("Archivo:", archivo.name)
    
    for hoja in ["BALANCE", "INDICADORES"]:
        print("-" * 60)
        print("Hoja:", hoja)
        
        temp = df_bancos_detectados[
            (df_bancos_detectados["archivo"] == archivo.name) &
            (df_bancos_detectados["hoja"] == hoja)
        ]
        
        for banco in temp["banco_original"].tolist():
            print("  -", banco)

====================================================================================================
Archivo: BOL BANCOS PRIVADOS 28022015 act.xlsx
------------------------------------------------------------
Hoja: BALANCE
  - BP GUAYAQUIL
  - BP PACIFICO
  - BP PICHINCHA
  - BP PRODUBANCO
  - BP AUSTRO
  - BP BOLIVARIANO
  - BP SOLIDARIO
  - BP GENERAL RUMIÑAHUI
  - BP INTERNACIONAL
  - BP MACHALA
  - BP CITIBANK
  - BP LOJA
  - BP PROCREDIT
  - BP AMAZONAS
  - BP COFIEC
  - BP COMERCIAL DE MANABI
  - BP LITORAL
  - BP COOPNACIONAL
  - BP CAPITAL
  - BP FINCA
  - BP DELBANK
  - BP D-MIRO S.A.
  - BP BANCODESARROLLO
------------------------------------------------------------
Hoja: INDICADORES
  - BP GUAYAQUIL
  - BP PACIFICO
  - BP PICHINCHA
  - BP PRODUBANCO
  - BP AUSTRO
  - BP BOLIVARIANO
  - BP SOLIDARIO
  - BP GENERAL RUMIÑAHUI
  - BP INTERNACIONAL
  - BP MACHALA
  - BP CITIBANK
  - BP LOJA
  - BP PROCREDIT
  - BP AMAZONAS
  - BP COFIEC
  - BP COMERCIAL DE MANABI
  - BP LITORAL
  - BP COOPNACIONAL
  - BP CAPITAL
  - BP FINCA
  - BP DELBANK
  - BP D-MIRO S.A.
  - BP BANCODESARROLLO
====================================================================================================
Archivo: FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
------------------------------------------------------------
Hoja: BALANCE
  - BP GUAYAQUIL
  - BP PACIFICO
  - BP PICHINCHA
  - BP PRODUBANCO
  - BP AUSTRO
  - BP BOLIVARIANO
  - BP CITIBANK
  - BP DINERS
  - BP GENERAL RUMIÑAHUI
  - BP INTERNACIONAL
  - BP LOJA
  - BP MACHALA
  - BP SOLIDARIO
  - BP PROCREDIT
  - BP AMAZONAS
  - BP BANCO COMERCIAL DE MANABI
  - BP LITORAL
  - BP COOPNACIONAL
  - BP CAPITAL
  - BP DELBANK
  - BANCO ATLÁNTIDA S.A.
  - BP BANCO  DESARROLLO DE LOS PUEBLOS  S.A., CODESARROLLO
  - BP VISIONFUND ECUADOR S.A.
------------------------------------------------------------
Hoja: INDICADORES
  - BP GUAYAQUIL
  - BP PACIFICO
  - BP PICHINCHA
  - BP PRODUBANCO
  - BP AUSTRO
  - BP BOLIVARIANO
  - BP CITIBANK
  - BP DINERS
  - BP GENERAL RUMIÑAHUI
  - BP INTERNACIONAL
  - BP LOJA
  - BP MACHALA
  - BP SOLIDARIO
  - BP PROCREDIT
  - BP AMAZONAS
  - BP BANCO COMERCIAL DE MANABI
  - BP LITORAL
  - BP COOPNACIONAL
  - BP CAPITAL
  - BP DELBANK
  - BANCO ATLÁNTIDA S.A.
  - BP BANCO  DESARROLLO DE LOS PUEBLOS  S.A., CODESARROLLO
  - BP VISIONFUND ECUADOR S.A.

INICIAMOS CON LA LIMPIEZA DE LOS DATOS NUMÉRICOS

In [47]:
INDICADORES_OBJETIVO = [
    {
        "indicador": "activos_total",
        "hoja": "BALANCE",
        "patrones_busqueda": [
            "TOTAL ACTIVO"
        ],
        "unidad": "miles_usd"
    },
    {
        "indicador": "morosidad_total",
        "hoja": "INDICADORES",
        "patrones_busqueda": [
            "MOROSIDAD DE LA CARTERA TOTAL"
        ],
        "unidad": "porcentaje_decimal"
    },
    {
        "indicador": "roe",
        "hoja": "INDICADORES",
        "patrones_busqueda": [
            "RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO"
        ],
        "unidad": "porcentaje_decimal"
    },
    {
        "indicador": "indice_capitalizacion_neto",
        "hoja": "INDICADORES",
        "patrones_busqueda": [
            "INDICE DE CAPITALIZACION NETO",
            "ÍNDICE DE CAPITALIZACIÓN NETO"
        ],
        "unidad": "porcentaje_decimal"
    },
    {
        "indicador": "suficiencia_patrimonial",
        "hoja": "INDICADORES",
        "patrones_busqueda": [
            "PATRIMONIO + RESULTADOS",
            "ACTIVOS INMOVILIZADOS NETOS",
            "ACTIVOS INMOVILIZADOS",
            "(3) (6)"
        ],
        "unidad": "porcentaje_decimal"
    }
]

In [48]:
# Función para limpiar valores numéricos
def limpiar_valor_numerico(valor):
    """
    Convierte valores provenientes de Excel a número.
    Soporta valores numéricos directos y textos con comas, espacios o símbolos.
    """
    
    if pd.isna(valor):
        return np.nan
    
    if isinstance(valor, (int, float, np.integer, np.floating)):
        return float(valor)
    
    texto = str(valor).strip()
    
    if texto == "":
        return np.nan
    
    # Quitar espacios
    texto = texto.replace(" ", "")
    
    # Quitar separadores de miles comunes
    texto = texto.replace(",", "")
    
    # Quitar símbolos no numéricos habituales
    texto = texto.replace("%", "")
    
    try:
        return float(texto)
    except ValueError:
        return np.nan

In [50]:
# Función para encontrar fila de un indicador
def encontrar_fila_indicador(archivo, hoja, patrones_busqueda):
    """
    Busca la fila donde se encuentra un indicador.
    Retorna el índice de fila base 0.
    
    Si patrones_busqueda tiene varios elementos, todos deben estar presentes
    en la misma fila normalizada.
    """
    
    df = pd.read_excel(
        archivo,
        sheet_name=hoja,
        header=None
    )
    
    patrones_norm = [normalizar_texto(p) for p in patrones_busqueda]
    
    for idx, fila in df.iterrows():
        texto_fila = " ".join(
            normalizar_texto(valor)
            for valor in fila
            if pd.notna(valor)
        )
        
        if all(patron in texto_fila for patron in patrones_norm):
            return idx
    
    return None

In [52]:
# Mostrar filas donde se encuentran los indicadores objetivo
for archivo in archivos_piloto:
    print("=" * 100)
    print("Archivo:", archivo.name)
    
    for config in INDICADORES_OBJETIVO:
        fila = encontrar_fila_indicador(
            archivo=archivo,
            hoja=config["hoja"],
            patrones_busqueda=config["patrones_busqueda"]
        )
        
        print(
            config["indicador"],
            "| Hoja:",
            config["hoja"],
            "| Fila Excel:",
            None if fila is None else fila + 1
        )

====================================================================================================
Archivo: BOL BANCOS PRIVADOS 28022015 act.xlsx
activos_total | Hoja: BALANCE | Fila Excel: 621
morosidad_total | Hoja: INDICADORES | Fila Excel: 25
roe | Hoja: INDICADORES | Fila Excel: 42
indice_capitalizacion_neto | Hoja: INDICADORES | Fila Excel: 75
suficiencia_patrimonial | Hoja: INDICADORES | Fila Excel: 11
====================================================================================================
Archivo: FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx
activos_total | Hoja: BALANCE | Fila Excel: 746
morosidad_total | Hoja: INDICADORES | Fila Excel: 27
roe | Hoja: INDICADORES | Fila Excel: 48
indice_capitalizacion_neto | Hoja: INDICADORES | Fila Excel: 80
suficiencia_patrimonial | Hoja: INDICADORES | Fila Excel: 11

In [53]:
# Función para extraer indicador desde un archivo
def extraer_indicador_archivo(archivo, config_indicador):
    """
    Extrae un indicador específico para todos los bancos detectados
    en la hoja correspondiente.
    """
    
    hoja = config_indicador["hoja"]
    indicador = config_indicador["indicador"]
    unidad = config_indicador["unidad"]
    patrones_busqueda = config_indicador["patrones_busqueda"]
    
    periodo = extraer_periodo_archivo(archivo)
    
    fila_indicador = encontrar_fila_indicador(
        archivo=archivo,
        hoja=hoja,
        patrones_busqueda=patrones_busqueda
    )
    
    if fila_indicador is None:
        print(f"⚠️ No se encontró indicador {indicador} en {archivo.name} - hoja {hoja}")
        return pd.DataFrame()
    
    bancos_hoja = extraer_bancos_hoja(archivo, hoja)
    
    if bancos_hoja.empty:
        print(f"⚠️ No se encontraron bancos en {archivo.name} - hoja {hoja}")
        return pd.DataFrame()
    
    df = pd.read_excel(
        archivo,
        sheet_name=hoja,
        header=None
    )
    
    registros = []
    
    for _, banco in bancos_hoja.iterrows():
        col_idx = int(banco["columna_excel_num"]) - 1
        
        valor = df.iloc[fila_indicador, col_idx]
        valor_limpio = limpiar_valor_numerico(valor)
        
        registros.append({
            "periodo": periodo,
            "banco_original": banco["banco_original"],
            "banco_normalizado": banco["banco_normalizado_preliminar"],
            "indicador": indicador,
            "valor": valor_limpio,
            "unidad": unidad,
            "archivo_origen": archivo.name,
            "hoja_origen": hoja,
            "fila_origen_excel": fila_indicador + 1,
            "columna_origen_excel": banco["columna_excel_num"]
        })
    
    return pd.DataFrame(registros)

In [54]:

# Función para procesar un archivo financiero completo
def procesar_archivo_financiero(archivo):
    """
    Procesa un archivo Excel financiero y extrae todos los indicadores objetivo.
    """
    
    dataframes = []
    
    for config in INDICADORES_OBJETIVO:
        df_indicador = extraer_indicador_archivo(
            archivo=archivo,
            config_indicador=config
        )
        
        if not df_indicador.empty:
            dataframes.append(df_indicador)
    
    if not dataframes:
        return pd.DataFrame()
    
    return pd.concat(dataframes, ignore_index=True)

In [56]:
# Procesar archivos piloto y construir dataset largo
dataset_long_piloto = []

for archivo in archivos_piloto:
    print("Procesando:", archivo.name)
    df_archivo = procesar_archivo_financiero(archivo)
    dataset_long_piloto.append(df_archivo)

dataset_long_piloto = pd.concat(dataset_long_piloto, ignore_index=True)

dataset_long_piloto.head(50)

Procesando: BOL BANCOS PRIVADOS 28022015 act.xlsx
Procesando: FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx

,periodo,banco_original,banco_normalizado,indicador,valor,unidad,archivo_origen,hoja_origen,fila_origen_excel,columna_origen_excel
0,2015-02,BP GUAYAQUIL,BP GUAYAQUIL,activos_total,3.956442e+06,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,4
1,2015-02,BP PACIFICO,BP PACIFICO,activos_total,4.470343e+06,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,5
2,2015-02,BP PICHINCHA,BP PICHINCHA,activos_total,9.510421e+06,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,6
3,2015-02,BP PRODUBANCO,BP PRODUBANCO,activos_total,3.737498e+06,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,7
4,2015-02,BP AUSTRO,BP AUSTRO,activos_total,1.533289e+06,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,9
5,2015-02,BP BOLIVARIANO,BP BOLIVARIANO,activos_total,2.748532e+06,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,10
6,2015-02,BP SOLIDARIO,BP SOLIDARIO,activos_total,7.315736e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,11
7,2015-02,BP GENERAL RUMIÑAHUI,BP GENERAL RUMINAHUI,activos_total,6.310042e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,12
8,2015-02,BP INTERNACIONAL,BP INTERNACIONAL,activos_total,2.598928e+06,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,13
9,2015-02,BP MACHALA,BP MACHALA,activos_total,6.901549e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,14
10,2015-02,BP CITIBANK,BP CITIBANK,activos_total,5.603044e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,15
11,2015-02,BP LOJA,BP LOJA,activos_total,4.508108e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,16
12,2015-02,BP PROCREDIT,BP PROCREDIT,activos_total,3.981634e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,17
13,2015-02,BP AMAZONAS,BP AMAZONAS,activos_total,1.423277e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,19
14,2015-02,BP COFIEC,BP COFIEC,activos_total,3.244445e+04,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,20
15,2015-02,BP COMERCIAL DE MANABI,BP COMERCIAL DE MANABI,activos_total,4.734986e+04,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,21
16,2015-02,BP LITORAL,BP LITORAL,activos_total,2.424788e+04,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,22
17,2015-02,BP COOPNACIONAL,BP COOPNACIONAL,activos_total,1.765327e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,23
18,2015-02,BP CAPITAL,BP CAPITAL,activos_total,1.613313e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,24
19,2015-02,BP FINCA,BP FINCA,activos_total,5.012961e+04,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,25
20,2015-02,BP DELBANK,BP DELBANK,activos_total,2.777916e+04,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,26
21,2015-02,BP D-MIRO S.A.,BP D-MIRO S.A.,activos_total,9.047422e+04,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,27
22,2015-02,BP BANCODESARROLLO,BP BANCODESARROLLO,activos_total,1.170692e+05,miles_usd,BOL BANCOS PRIVADOS 28022015 act.xlsx,BALANCE,621,28
23,2015-02,BP GUAYAQUIL,BP GUAYAQUIL,morosidad_total,2.959304e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,4
24,2015-02,BP PACIFICO,BP PACIFICO,morosidad_total,3.570528e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,5
25,2015-02,BP PICHINCHA,BP PICHINCHA,morosidad_total,4.580700e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,6
26,2015-02,BP PRODUBANCO,BP PRODUBANCO,morosidad_total,2.378228e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,7
27,2015-02,BP AUSTRO,BP AUSTRO,morosidad_total,5.737171e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,9
28,2015-02,BP BOLIVARIANO,BP BOLIVARIANO,morosidad_total,1.284305e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,10
29,2015-02,BP SOLIDARIO,BP SOLIDARIO,morosidad_total,8.165448e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,11
30,2015-02,BP GENERAL RUMIÑAHUI,BP GENERAL RUMINAHUI,morosidad_total,3.659497e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,12
31,2015-02,BP INTERNACIONAL,BP INTERNACIONAL,morosidad_total,1.914350e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,13
32,2015-02,BP MACHALA,BP MACHALA,morosidad_total,2.671883e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,14
33,2015-02,BP CITIBANK,BP CITIBANK,morosidad_total,1.675633e-05,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,15
34,2015-02,BP LOJA,BP LOJA,morosidad_total,3.883285e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,16
35,2015-02,BP PROCREDIT,BP PROCREDIT,morosidad_total,3.599824e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,17
36,2015-02,BP AMAZONAS,BP AMAZONAS,morosidad_total,5.652358e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,19
37,2015-02,BP COFIEC,BP COFIEC,morosidad_total,8.750430e+01,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,20
38,2015-02,BP COMERCIAL DE MANABI,BP COMERCIAL DE MANABI,morosidad_total,6.010262e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,21
39,2015-02,BP LITORAL,BP LITORAL,morosidad_total,1.184911e+01,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,22
40,2015-02,BP COOPNACIONAL,BP COOPNACIONAL,morosidad_total,3.758848e-01,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,23
41,2015-02,BP CAPITAL,BP CAPITAL,morosidad_total,7.954409e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,24
42,2015-02,BP FINCA,BP FINCA,morosidad_total,6.561314e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,25
43,2015-02,BP DELBANK,BP DELBANK,morosidad_total,6.213564e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,26
44,2015-02,BP D-MIRO S.A.,BP D-MIRO S.A.,morosidad_total,6.005200e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,27
45,2015-02,BP BANCODESARROLLO,BP BANCODESARROLLO,morosidad_total,6.164210e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,25,28
46,2015-02,BP GUAYAQUIL,BP GUAYAQUIL,roe,1.112692e+01,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,42,4
47,2015-02,BP PACIFICO,BP PACIFICO,roe,9.617102e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,42,5
48,2015-02,BP PICHINCHA,BP PICHINCHA,roe,1.020504e+01,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,42,6
49,2015-02,BP PRODUBANCO,BP PRODUBANCO,roe,7.753672e+00,porcentaje_decimal,BOL BANCOS PRIVADOS 28022015 act.xlsx,INDICADORES,42,7

In [57]:
# Verificar estructura del dataset largo
dataset_long_piloto.shape

(230, 10)

In [58]:
# Resumen de datos extraídos por periodo, archivo e indicador
dataset_long_piloto.groupby(["periodo", "archivo_origen", "indicador"]).agg(
    cantidad_bancos=("banco_normalizado", "count"),
    valores_nulos=("valor", lambda x: x.isna().sum())
).reset_index()

,periodo,archivo_origen,indicador,cantidad_bancos,valores_nulos
0,2015-02,BOL BANCOS PRIVADOS 28022015 act.xlsx,activos_total,23,0
1,2015-02,BOL BANCOS PRIVADOS 28022015 act.xlsx,indice_capitalizacion_neto,23,0
2,2015-02,BOL BANCOS PRIVADOS 28022015 act.xlsx,morosidad_total,23,0
3,2015-02,BOL BANCOS PRIVADOS 28022015 act.xlsx,roe,23,0
4,2015-02,BOL BANCOS PRIVADOS 28022015 act.xlsx,suficiencia_patrimonial,23,0
5,2026-03,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,activos_total,23,0
6,2026-03,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,indice_capitalizacion_neto,23,0
7,2026-03,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,morosidad_total,23,0
8,2026-03,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,roe,23,0
9,2026-03,FINANCIERO MENSUAL BANCA PRIVADA 2026_03.xlsx,suficiencia_patrimonial,23,0

In [59]:
# Mostrar filas donde se encuentran categorías agregadas
dataset_long_piloto[
    dataset_long_piloto["banco_normalizado"].str.contains(
        "TOTAL|GRANDES|MEDIANOS|PEQUENOS|PEQUEÑOS|COMERCIALES|CONSUMO|VIVIENDA|MICROCREDITO|MICROCRÉDITO|MULTIPLE|MÚLTIPLE",
        case=False,
        na=False
    )
]

Empty DataFrame
Columns: [periodo, banco_original, banco_normalizado, indicador, valor, unidad, archivo_origen, hoja_origen, fila_origen_excel, columna_origen_excel]
Index: []

In [60]:
# Pivotar dataset largo a formato ancho
dataset_wide_piloto = dataset_long_piloto.pivot_table(
    index=[
        "periodo",
        "banco_normalizado",
        "banco_original",
        "archivo_origen"
    ],
    columns="indicador",
    values="valor",
    aggfunc="first"
).reset_index()

dataset_wide_piloto.columns.name = None

dataset_wide_piloto.head(20)

,periodo,banco_normalizado,banco_original,archivo_origen,activos_total,indice_capitalizacion_neto,morosidad_total,roe,suficiencia_patrimonial
0,2015-02,BP AMAZONAS,BP AMAZONAS,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.423277e+05,11.796559,5.652358,5.934340,186.988317
1,2015-02,BP AUSTRO,BP AUSTRO,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.533289e+06,7.808395,5.737171,7.297751,166.889954
2,2015-02,BP BANCODESARROLLO,BP BANCODESARROLLO,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.170692e+05,9.586394,6.164210,14.517626,219.917000
3,2015-02,BP BOLIVARIANO,BP BOLIVARIANO,BOL BANCOS PRIVADOS 28022015 act.xlsx,2.748532e+06,7.367603,1.284305,12.064456,271.104736
4,2015-02,BP CAPITAL,BP CAPITAL,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.613313e+05,9.446750,7.954409,0.650763,85.921398
5,2015-02,BP CITIBANK,BP CITIBANK,BOL BANCOS PRIVADOS 28022015 act.xlsx,5.603044e+05,9.458344,0.000017,11.770895,-458.279560
6,2015-02,BP COFIEC,BP COFIEC,BOL BANCOS PRIVADOS 28022015 act.xlsx,3.244445e+04,11.040637,87.504301,-32.019146,49.811243
7,2015-02,BP COMERCIAL DE MANABI,BP COMERCIAL DE MANABI,BOL BANCOS PRIVADOS 28022015 act.xlsx,4.734986e+04,13.229871,6.010262,0.642043,133.260329
8,2015-02,BP COOPNACIONAL,BP COOPNACIONAL,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.765327e+05,12.672209,0.375885,11.000514,2837.342836
9,2015-02,BP D-MIRO S.A.,BP D-MIRO S.A.,BOL BANCOS PRIVADOS 28022015 act.xlsx,9.047422e+04,14.484615,6.005200,10.951209,357.285730
10,2015-02,BP DELBANK,BP DELBANK,BOL BANCOS PRIVADOS 28022015 act.xlsx,2.777916e+04,32.838227,6.213564,-0.494398,351.858869
11,2015-02,BP FINCA,BP FINCA,BOL BANCOS PRIVADOS 28022015 act.xlsx,5.012961e+04,16.287291,6.561314,-32.096326,283.853390
12,2015-02,BP GENERAL RUMINAHUI,BP GENERAL RUMIÑAHUI,BOL BANCOS PRIVADOS 28022015 act.xlsx,6.310042e+05,6.976345,3.659497,20.823774,-774.299342
13,2015-02,BP GUAYAQUIL,BP GUAYAQUIL,BOL BANCOS PRIVADOS 28022015 act.xlsx,3.956442e+06,8.193314,2.959304,11.126918,172.086857
14,2015-02,BP INTERNACIONAL,BP INTERNACIONAL,BOL BANCOS PRIVADOS 28022015 act.xlsx,2.598928e+06,7.777538,1.914350,11.326130,525.593273
15,2015-02,BP LITORAL,BP LITORAL,BOL BANCOS PRIVADOS 28022015 act.xlsx,2.424788e+04,14.062494,11.849112,4.205340,249.637093
16,2015-02,BP LOJA,BP LOJA,BOL BANCOS PRIVADOS 28022015 act.xlsx,4.508108e+05,8.230680,3.883285,10.387775,1875.997267
17,2015-02,BP MACHALA,BP MACHALA,BOL BANCOS PRIVADOS 28022015 act.xlsx,6.901549e+05,6.483733,2.671883,5.659041,135.243990
18,2015-02,BP PACIFICO,BP PACIFICO,BOL BANCOS PRIVADOS 28022015 act.xlsx,4.470343e+06,10.393331,3.570528,9.617102,351.568821
19,2015-02,BP PICHINCHA,BP PICHINCHA,BOL BANCOS PRIVADOS 28022015 act.xlsx,9.510421e+06,8.330506,4.580700,10.205044,2123.152731

In [61]:
dataset_wide_piloto.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   periodo                     46 non-null     str
 1   banco_normalizado           46 non-null     str
 2   banco_original              46 non-null     str
 3   archivo_origen              46 non-null     str
 4   activos_total               46 non-null     float64
 5   indice_capitalizacion_neto  46 non-null     float64
 6   morosidad_total             46 non-null     float64
 7   roe                         46 non-null     float64
 8   suficiencia_patrimonial     46 non-null     float64
dtypes: float64(5), str(4)
memory usage: 3.4 KB

In [62]:
dataset_wide_piloto.head()

,periodo,banco_normalizado,banco_original,archivo_origen,activos_total,indice_capitalizacion_neto,morosidad_total,roe,suficiencia_patrimonial
0,2015-02,BP AMAZONAS,BP AMAZONAS,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.423277e+05,11.796559,5.652358,5.934340,186.988317
1,2015-02,BP AUSTRO,BP AUSTRO,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.533289e+06,7.808395,5.737171,7.297751,166.889954
2,2015-02,BP BANCODESARROLLO,BP BANCODESARROLLO,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.170692e+05,9.586394,6.164210,14.517626,219.917000
3,2015-02,BP BOLIVARIANO,BP BOLIVARIANO,BOL BANCOS PRIVADOS 28022015 act.xlsx,2.748532e+06,7.367603,1.284305,12.064456,271.104736
4,2015-02,BP CAPITAL,BP CAPITAL,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.613313e+05,9.446750,7.954409,0.650763,85.921398

CALCULAR RANKINGS BASICOS POR PERIODO

In [63]:
dataset_wide_piloto["rank_activos"] = dataset_wide_piloto.groupby("periodo")["activos_total"] \
    .rank(ascending=False, method="dense")

dataset_wide_piloto["rank_roe"] = dataset_wide_piloto.groupby("periodo")["roe"] \
    .rank(ascending=False, method="dense")

dataset_wide_piloto["rank_morosidad"] = dataset_wide_piloto.groupby("periodo")["morosidad_total"] \
    .rank(ascending=True, method="dense")

dataset_wide_piloto["rank_capitalizacion"] = dataset_wide_piloto.groupby("periodo")["indice_capitalizacion_neto"] \
    .rank(ascending=False, method="dense")

dataset_wide_piloto.head()

,periodo,banco_normalizado,banco_original,archivo_origen,activos_total,indice_capitalizacion_neto,morosidad_total,roe,suficiencia_patrimonial,rank_activos,rank_roe,rank_morosidad,rank_capitalizacion
0,2015-02,BP AMAZONAS,BP AMAZONAS,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.423277e+05,11.796559,5.652358,5.934340,186.988317,16.0,14.0,13.0,9.0
1,2015-02,BP AUSTRO,BP AUSTRO,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.533289e+06,7.808395,5.737171,7.297751,166.889954,7.0,13.0,14.0,18.0
2,2015-02,BP BANCODESARROLLO,BP BANCODESARROLLO,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.170692e+05,9.586394,6.164210,14.517626,219.917000,17.0,2.0,17.0,12.0
3,2015-02,BP BOLIVARIANO,BP BOLIVARIANO,BOL BANCOS PRIVADOS 28022015 act.xlsx,2.748532e+06,7.367603,1.284305,12.064456,271.104736,5.0,3.0,3.0,20.0
4,2015-02,BP CAPITAL,BP CAPITAL,BOL BANCOS PRIVADOS 28022015 act.xlsx,1.613313e+05,9.446750,7.954409,0.650763,85.921398,15.0,19.0,20.0,14.0

In [64]:
# Guardar datasets procesados
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

ruta_long = PROCESSED_DIR / "dataset_financiero_long_piloto.csv"
ruta_wide = PROCESSED_DIR / "dataset_financiero_wide_piloto.csv"

dataset_long_piloto.to_csv(ruta_long, index=False, encoding="utf-8-sig")
dataset_wide_piloto.to_csv(ruta_wide, index=False, encoding="utf-8-sig")

print("Guardado:", ruta_long)
print("Guardado:", ruta_wide)

Guardado: c:\Users\Gladys\Documents\Eddy\Seminario Python\proyecto_bancos\data\processed\dataset_financiero_long_piloto.csv
Guardado: c:\Users\Gladys\Documents\Eddy\Seminario Python\proyecto_bancos\data\processed\dataset_financiero_wide_piloto.csv